### ISSUE TITLE
IntrospectionFragmentMatcher works without providing types

### ISSUE THREAD

**Issue by benjarwar** [apollographql/apollo-feature-requests#10]
Migrated from: apollographql/apollo-client#3397

This isn't so much a feature request as an observation that the `IntrospectionFragmentMatcher` seems to work without providing types explicitly, which runs counter to the documentation. Details in the original issue, which has been closed.

**Comment by hwillson** [comment]
Re-opened in https://github.com/apollographql/apollo-client/issues/3397 as a bug. Thanks!
