### ISSUE TITLE
Provide named fragment definitions to client resolvers [will contribute code]

### ISSUE THREAD

**Issue by mjlyons** [apollographql/apollo-feature-requests#110]
I'm submitting this feature request as a proposal -- if the proposal works the team I'll follow up with a PR. If there are better alternatives, I may be able to take those on instead.

---

The `info` parameter passed to client resolvers only includes the AST for the current field (and its defendants). This makes determining field selection lookahead impossible when named fragments are used:

```
fragment MyNamedFragment on MyType {
  myFieldByFragment
}
query MyQuery {
  myQueryThatReturnsMyType @client {
    myFieldByFieldName
    ...MyNamedFragment
  }
}
```

In the example above, a client resolver for `myQueryThatReturnsMyType` could determine that `myFieldByFieldName` will be selected on the result. It will also know that the fields from `MyNamedFragment` will be selected. However, it cannot determine which fields will be selected from `MyNamedFragment` because `MyNamedFragment` is defined outside of `myQueryThatReturnsMyType`'s AST.

There's a few approaches that could be taken (and I'm happy to expand on them), but the simplest seems to be passing `fragmentMap` through the `info` parameter or the `context` parameter. `fragmentMap` maintains a map of named fragment names to their ASTs. If a resolver had access to `fragmentMap`, it could then determine which fields will be selected by named fragment.

If this solution is acceptable to the team, it could be as simple as changing the line at https://github.com/apollographql/apollo-client/blob/b022ea3695e8469cd86f32526b075cd32ae2853f/packages/apollo-client/src/core/LocalState.ts#L395

from:
```
          resultPromise = Promise.resolve(resolve(
            rootValue,
            argumentsObjectFromField(field, variables),
            execContext.context,
            { field },
          ));
```

to
```
          resultPromise = Promise.resolve(resolve(
            rootValue,
            argumentsObjectFromField(field, variables),
            execContext.context,
            { field, fragmentMap },
          ));
```

I patched this change in locally for my project and it works great. 

If this works for you, I'd be happy to submit a PR.

Thanks,
Mike

**Comment by hwillson** [comment]
Great idea @mjlyons - we'd definitely review a PR for this. Thanks!

**Comment by jpvajda** [comment]
closing as this PR was merged.
