### ISSUE TITLE
«skip» option for useSubscription

### ISSUE THREAD

**Issue by Rusya44** [apollographql/apollo-feature-requests#121]
Would love to see «skip» option for `useSubscription` like on `useQuery`. Now my workaround is to use `Subscription` component which can be rendered conditionally.

**Comment by n1ru4l** [comment]
I tried to tackle this one in https://github.com/apollographql/react-apollo/pull/3356

**Comment by hwillson** [comment]
Thanks to @n1ru4l and https://github.com/apollographql/react-apollo/pull/3356, this functionality is coming in the next release (today or this weekend).

**Comment by zhengren88** [comment]
Any update on this feature request?

**Comment by SnapeEye** [comment]
Found the stack topic with related question: [LINK](https://stackoverflow.com/questions/61370645/how-to-conditionally-run-usesubscription-hook-of-apollo-client)

There was a comment that skip param is already working. BUT - the doc is not updated.
Didn't test it by myself, just researching this topic)

**Comment by cbissa** [comment]
> use `Subscription` component which can be rendered conditionally.

can u help me with this how to do that.
