### ISSUE TITLE
Feature Idea: Support subscriptions in Apollo-boost

### ISSUE THREAD

**Issue by Akryum** [apollographql/apollo-feature-requests#13]
Migrated from: apollographql/apollo-client#3024

**Comment by jerelmiller** [comment]
Hey @Akryum 👋 

This issue is pretty old by now and `apollo-boost` has since been deprecated. I'm going to go ahead and close this issue. Feel free to open a new feature request for more modern versions of Apollo Client if you have additional ideas. Thanks!
