### ISSUE TITLE
`installSubscriptionHandlers` can't coexist with other websockets on the same port

### ISSUE THREAD

**Issue by jedwards1211** [apollographql/apollo-feature-requests#134]
I'm trying to add a websocket for GraphQL subscriptions alongside a Meteor DDP connection.
Unfortunately, `WebSocket.Server` aborts the handshake for any `upgrade` request it receives for a different path than the one configured in my `ApolloServer`, so it breaks Meteor's DDP websocket.

It's possible to support two websockets on the same port/different paths by writing an `upgrade` listener that decides whether to forward the event to the `WebSocket.Server` for Apollo or ignore it and let Meteor DDP handle it.  However, to do that I have to copy code out of `ApolloServer.installSubscriptionHandlers` (which could change in the future) so that I can pass my own `WebSocket.Server` instance to `SubscriptionServer.create`.

This is an unhappy workaround.  Could we at least make it possible to pass our own `WebSocket.Server` to `installSubscriptionHandlers`?  Or is there another way to make `ApolloServer` more flexible?  I didn't have this problem with `apollo-server-express` v1 because it was a much less monolithic API.

I also asked for an option to ignore `upgrade` requests for other paths in `WebSocket.Server`: https://github.com/websockets/ws/issues/1193#issuecomment-438826565.  If that becomes a reality we would simply need a way to pass that option through.

**Comment by taozhi8833998** [comment]
same issue

**Comment by ananthachetan** [comment]
When can we expect the fix for this? We are incrementally incorporating subscriptions into our setup which already has websockets using SocketIO and ran into this problem.

**Comment by lambdahands** [comment]
It took me hours to get to this issue as the problem this behavior caused was so indirect. I'm looking at the workaround, and it seems like it requires me to re-architect a much simpler `ApolloServer` setup into something more piecemeal. Are there any plans to augment `installSubscriptionHandlers` with something like a `{path: "/graphql"}` option so it doesn't override _every_ WebSocket request?

**Comment by ruohki** [comment]
running into this as well

**Comment by trevor-scheer** [comment]
Subscriptions over websockets are no longer an Apollo Server concern as of v4, so any outstanding issues with using them would need to be taken up with the respective libraries (apparently `ws`) that you might be using.
