### ISSUE TITLE
[FEAT] Pass Apollo Link to GraphQL Playground

### ISSUE THREAD

**Issue by evans** [apollographql/apollo-feature-requests#137]
I'd like to be able to pass an apollo-link to GraphQL playground in order to set the client header for my graphql request, as documented in the Platform's [Client Awareness docs](https://www.apollographql.com/docs/platform/client-awareness.html). While it is possible to add the headers manually, ensuring that a default client name and default version are used every time would be great.

**Comment by jerelmiller** [comment]
Hey @evans 👋 

We have shifted this repo to be specific to the [Apollo TypeScript Client](https://github.com/apollographql/apollo-client). As such, I'm going to go ahead and close this issue.

If you're still in need of assistance or would like to raise this request again, please open an issue in the [Apollo Studio Community repo](https://github.com/apollographql/apollo-studio-community). Thanks!
