### ISSUE TITLE
Allow RESTDataSource to use a custom fetch function

### ISSUE THREAD

**Issue by jbachhardie** [apollographql/apollo-feature-requests#140]
We have a practice of wrapping HTTP calls to other internal services in [Circuit Breakers](http://martinfowler.com/bliki/CircuitBreaker.html). This is very easy to do with `HTTPLink` since it takes a fetch function as an option. However, looking into using DataSources there doesn't seem to be any way of achieving something equivalent with `RESTDataSource`. The call to fetch happens inside the `HTTPCache` class which always imports the same global `fetch` function.

It would be really helpful not only for implementing circuit breakers but I'm sure other specifics to be able to configure `RESTDataSource` with a custom `fetch` function.

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-server/pull/1807 has been merged. This feature will be coming in the next AS release. Thanks very much @jbachhardie!
