### ISSUE TITLE
[Feature Request] Make (federated) service introspection optional for serverless applications

### ISSUE THREAD

**Issue by martinjlowm** [apollographql/apollo-feature-requests#143]
In serverless applications, introspection is quite an overhead and as of now, this step is required to build a schema for the gateway.

What We do now to work around it (with the old schema stitching) is to pull schemas at build time and ship the services' schemas with a new deployment of the gateway.

This has become a bit more tricky with Apollo Federation, but is still possible to some degree by specifying these schemas as local services (`localServiceList`) and a custom data source to control how to communicate with the external endpoint(s).

I'd suggest some way to override `@apollo/gateway`'s initialization behavior with some serverless functionality that may be used by Azure-, cloud- and Lambda functions to supply schema and endpoint without having to communicate with each federated service, individually.

On top of that, we also use custom directives to supply authorization at the gateway-level (#2778) (then usable at the service-level) - and there's currently no way to supply custom directives with the federation feature which makes schema validation fail using `localServiceList`.

**Comment by mugtaba-subahi** [comment]
@jbaxleyiii do you know where i can find the documentation for this? cheers

**Comment by harnit-bakshi** [comment]
Hi any update on this :)

**Comment by gabsn** [comment]
Hi, I may have found a workaround with the supergraphs although it doesn't seem production ready yet.

See my explanation here: https://github.com/mugtaba-subahi/serverless-apollo-federation/issues/11#issue-928547840

I will try it in a real-world app soon. Will tell you how it goes.

**Comment by trevor-scheer** [comment]
This is the default workflow for router + rover, and can be accomplished in `@apollo/gateway` using [`SupergraphManager`](https://www.apollographql.com/docs/apollo-server/using-federation/api/apollo-gateway/#supergraphsdl)s
