### ISSUE TITLE
Support async functions in CacheRedirects Query 

### ISSUE THREAD

**Issue by Hasan-git** [apollographql/apollo-feature-requests#146]
CacheRedirects Query doesn't work with Asynchronous  function

![image](https://user-images.githubusercontent.com/8820596/60721534-f5a82a80-9f36-11e9-9f91-c7201c9d180a.png)

**Comment by jerelmiller** [comment]
Hey there 👋 

I'm doing a quick sweep of some old issues and came across this one which looks like its a request on the [v2 cache API](https://www.apollographql.com/docs/react/v2/caching/cache-configuration). I'm going to go ahead and close this one now that `cacheRedirects` is no longer an option in v3. Thanks!
