### ISSUE TITLE
initialState support in apollo-boost

### ISSUE THREAD

**Issue by gfpacheco** [apollographql/apollo-feature-requests#15]
Migrated from: apollographql/apollo-client#3340

**Intended outcome:**

I wanted to pass a ssr-generated initial state to `InMemoryCache`. Something like this:

```
new ApolloClient({
  uri: '...',
  initialState: window.__APOLLO_STATE__,
});
```

**Actual outcome:**
The current apollo-boost client only accepts the `cacheRedirects` option for the `InMemoryCache`

**Version**
- apollo-client@0.1.4

**Comment by jerelmiller** [comment]
Hey @gfpacheco 👋 

I know this issue is pretty old by now and `apollo-boost` has since been deprecated. I'm going to go ahead and close this issue. Feel free to open a new feature request if you have additional ideas/suggestions for more modern versions of Apollo Client. Thanks!
