### ISSUE TITLE
react-apollo Error: Network error: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by robinia1200** [apollographql/apollo-feature-requests#153]
I want to send a request to this server via Apollo and get a query :

const client = new ApolloClient({
  link: new HttpLink({
    uri:'http://mfapat.com/graphql/mfaapp/'}),
    cache: new InMemoryCache()

})

const FeedQuery = gql
  query{
  allFmr{
    fmrId,
    name,
    studio,
    bedRm1,
    bedRm2,
    bedRm3,
    bedRm4
  }
}
` But I'm facing this error message:

Unhandled (in react-apollo:Apollo(FMRScreen)) Error: Network error: Unexpected token < in JSON at position 1

at new ApolloError (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:109336:32)
at ObservableQuery.currentResult (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:109447:28)
at GraphQL.dataForChild (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:103192:66)
at GraphQL.render (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:103243:37)
....

But I can easily open "http://mfapat.com/graphql/mfaapp/" in my browser and get a query. Does anyone know where the problem is?

**Intended outcome:**

**Actual outcome:**

**How to reproduce the issue:**

**Version**
- apollo-client@<version number>

**Comment by trcolgrove** [comment]
We're definitely seeing a lot of this as well. Would be good to have a built in way to handle these.

**Comment by monjohn** [comment]
Agree with btff above: 

https://github.com/apollographql/apollo-feature-requests/issues/153#issuecomment-419689501

Better to check the response type and only try to parse body as JSON when appropriate.

**Comment by moneco-hub** [comment]
I had the same problem working with django as back-end, that's because i was sending a POST request without "crsf token". I solved this problem removing 'django.middleware.csrf.CsrfViewMiddleware' from the  MIDDLEWARE in the settings.py.

**Comment by johnpaul89** [comment]
It worked too on mine, but by removing 'django.middleware.csrf.CsrfViewMiddleware' will this affect security of your website by exposing Cross Site Request Forgery protection @moneco-hub

**Comment by moneco-hub** [comment]
@johnpaul89 , yes, you're righ, but at lest it will allow you continue your development while you (we) find the solution. Please, let me know when you find it.

**Comment by moneco-hub** [comment]
@johnpaul89, it works for me.

from django.contrib import admin
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt
from django.urls import path

urlpatterns = [
    path('', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('admin/', admin.site.urls),
]

**Comment by johnpaul89** [comment]
Currently I'm using this to replace the removed middleware

[https://docs.djangoproject.com/en/3.0/ref/csrf/#django.views.decorators.csrf.csrf_protect](url)

While on graphql, I'm using this as url from this reply [https://github.com/graphql-python/graphene-django/issues/593#issuecomment-477378015](url)

path('graphql/', jwt_cookie(FileUploadGraphQLView.as_view(graphiql=True))),

**Comment by cc-dev-leader** [comment]
Hi everyone. I solved this issue using useLazyQuery over useQuery.
My code: 

```const [ accesses, setAccesses ] = useState(null);
  const [ getAccess ] = useLazyQuery(ACCESS_LIST, {
    onCompleted: data => {
      setAccesses(data.accessList);
    }
  });

  useEffect(() => {
    getAccesses();
  }, []);```

**Comment by riturajratan** [comment]
Hi guys,
I am using this configuration and graphql is working fine still getting same error :(
```
const client = new ApolloClient({
  uri: "http://localhost:3000/graphql" // or your graphql server uri
});
```

please, someone, suggest to me how will it resolve it?

**Comment by riturajratan** [comment]
> I'm having the same error message but my server is fine. I can run the queries in graphql playground without any issues. What else could be causing this? Is there any way to debug it further?



have you found any solution? I am getting the same issue

**Comment by rraabe** [comment]
@riturajratan Check this [thread](https://github.com/apollographql/apollo-client/issues/3421). If you're importing ApolloClient from apollo-boost then not all the options exist on your client and using createHttpLink won't change the uri. 

Check your browser's network tab and see if your graphql requests are being made to the uri you're expecting. In my case, I was specifying http://localhost:4001/graphql but the request was being made to http://localhost:3000/graphql. The response that being sent back was an HTML 404 error code and Apollo was trying to parse it as if it were JSON (hence the error). Changing my import statement fixed the issue.

**Comment by jcharnley** [comment]
> A work around is to provide a fetch handler to [Apollo Http Link](https://www.apollographql.com/docs/link/links/http) that will check for errors and return something that Apollo can handle:
> 
> ```
> const customFetch = (uri, options) => {
>   return fetch(uri, options)
>   .then(response => {
>     if (response.status >= 500) {  // or handle 400 errors
>       return Promise.reject(response.status);
>     }
>     return response;
>   });
> };
> const client = new ApolloClient({
>   link: createHttpLink({
>     uri: "/graphql",
>     fetch: customFetch,
>   }),
>   cache: new InMemoryCache()
> });
> ```
Thanks for that solution works a treat

**Comment by azuxx** [comment]
Hello, I have the same issue using version 3.0.0-beta.43.

Here's my details:

latest console.log (After being logged in, user is not confirmed so I am redirecting to this ConfirmEmailScreen where I am doing a lazy query polling every 5secs and after some I got the issue)

```
authentication.ts:26 {access-token: "CIBBhg9Y-W2QQrQoIQlIIQ", client: "htH6v6_UMpm6UAtbgFhfdw", token-type: "Bearer", expiry: "1588783816", uid: "tenehi1043@emailhost99.com"}
SignIn.tsx:64 {data: {…}}
ConfirmEmail.tsx:53 exit condition not true yet. continue polling
AuthNavigator.tsx:42 AuthNavigator got signedIn, so updated navigation...
ConfirmEmail.tsx:40 started polling
ConfirmEmail.tsx:53 exit condition not true yet. continue polling
authentication.ts:26 {access-token: "ZsYqtJkfw_3LVIv1YQGm4g", client: "1F7yOM_2RkFC0L6Wg5e0AQ", token-type: "Bearer", expiry: "1588784117", uid: "tenehi1043@emailhost99.com"}
2ConfirmEmail.tsx:53 exit condition not true yet. continue polling
authentication.ts:26 {access-token: "ZsYqtJkfw_3LVIv1YQGm4g", client: "1F7yOM_2RkFC0L6Wg5e0AQ", token-type: "Bearer", expiry: "1588784117", uid: "tenehi1043@emailhost99.com"}
apollo-client.ts:28 [Network error]: ServerParseError: Unexpected token < in JSON at position 0
ConfirmEmail.tsx:47 error! stopped polling
```

and the code:

```javascript
const ConfirmEmailScreen = ({navigation}) => {
  const {emailConfirmed} = React.useContext(AuthContext);
  const _isPolling = useRef(false);

  const [
    getUserMe,
    {loading: loadingUserMe, error, data: dataUserMe, stopPolling}
  ] = useLazyQuery(QUERY_USER_ME, {
    pollInterval: 5000
  });

  const [userResendConfirmationEmail, {loading: resendLoading}] = useMutation(
    MUTATION_USER_RESEND_CONFIRMATION
  );

  const onResendPress = () => {
    userResendConfirmationEmail()
      .then((res) => {
        console.log(res);
      })
      .catch((reason) => {
        console.log(reason);
      });
  };

  useEffect(() => {
    if (!_isPolling.current) {
      console.log('started polling');
      getUserMe();
      _isPolling.current = true;
    }
  });

  if (error) {
    console.log('error! stopped polling');
    stopPolling();
  } else if (dataUserMe && dataUserMe.me && !!dataUserMe.me.confirmedAt) {
    stopPolling();
    emailConfirmed(dataUserMe.me);
  } else {
    console.log('exit condition not true yet. continue polling');
  }

  return (
    <SafeAreaView style={[styles.containerPadding, styles.contentCentered]}>
      <Text style={[styles.mb16, styles.textCenter]}>
        We sent an email. Please check your mailbox at{' '}
        {dataUserMe && dataUserMe.me ? dataUserMe.me.email : ''}
      </Text>
      {!error ? (
        <ActivityIndicator
          style={styles.mb16}
          animating={true}
          color={Colors.black}
        />
      ) : null}
      {error ? (
        <Text style={[styles.errorText, styles.mt16]}>
          Server/Apollo error, polling has been stopped
        </Text>
      ) : null}
      <Button mode="contained" loading={resendLoading} onPress={onResendPress}>
        Send again
      </Button>
    </SafeAreaView>
  );
};
```

Do you have any suggestions?🙏🏻 Or am I doing something wrong?

**Comment by Patricio18** [comment]
I have the same error but I deployment my server-app in heroku this server work but when try the connect me from my app in react-native, show me the screen initial but i want SignIn and I have this error: 
react-apollo Error: Network error: Unexpected token < in JSON

**Comment by azuxx** [comment]
@Patricio18 I found out the code is correct and it was due to a server issue (an experimental feature active on Apollo Rails side). This error represents a "right" parsing error of a html page, a redirect response.
Flipper debugger (standalone app) helped my network troubleshooting a lot🙌.
Hope this helps.

**Comment by RadiksMan** [comment]
For myself, I solved the problem of showing custom errors from the server

**Comment by RadiksMan** [comment]
For myself, I solved the problem of showing custom errors from the server:
you need add **accept: 'application/json'** to apollo headers request;
then if you catch error - stringify it ( JSON.stringify(error, null, 2)) ) to to find out all available properties
```javascript
"graphQLErrors": [],
"networkError": {
  "name": "ServerError",
  "response": {
    "type": "default",
    "status": 401,
    "ok": false,
    "headers": {
      "map": {
        "server": "nginx/1.14.0 (Ubuntu)",
        ...
      }
    },
    "url": “…./graphql/contest",
    "bodyUsed": true
  },
  "statusCode": 401,
  "result": {
    "message": "Token Signature could not be verified.",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\UnauthorizedHttpException",
    "file": "...vendor/tymon/jwt-auth/src/Http/Middleware/BaseMiddleware.php",
    "line": 74,
    "trace": [
      {
        "file": "...vendor/tymon/jwt-auth/src/Http/Middleware/Authenticate.php",
        "line": 30,
        "function": "authenticate",
        "class": "Tymon\\JWTAuth\\Http\\Middleware\\BaseMiddleware",
        "type": "->"
      },
      ...
    }]
  }
  },
  "message": "Network error: Response not successful: Received status code 401"
```
without indication accept: 'application/json'  i was getting html-content error

**Comment by StKostyantin** [comment]
I get data in the status of 200, and everything is displayed normally, but any error that comes is not processed by the Apollo and writes the error:
 "Error:" Network error: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data "

Although I get this error in status 200
`{"errors": [{"message": "Provided JWT token is invalid", "locations": [{"line": 2, "column": 3}], "path": ["user"], " extensions ": {" details ":" Wrong JWt "}}]}`

`const linkHttp = new HttpLink({
  uri: 'http://localhost:3033/graphql',
  // uri: 'https://api.graph.cool/simple/v1/cixmkt2ul01q00122mksg82pn', // Server URL (must be absolute)
  headers: {
    // 'Access-Control-Allow-Origin': '*',
    Authorization: `Bearer `,
    accept: 'application/json',
    'Content-Type': 'application/json'
  },
  ...(process.env.NODE_ENV !== 'production'
    ? { fetchOptions: {
        mode: 'no-cors',
      } } : {}),
  credentials: 'same-origin' // Additional fetch() options like `credentials` or `headers`
})

const client = new ApolloClient({
  link: ApolloLink.from([
    linkError,
    linkHttp
]),
  cache: new InMemoryCache()
});`

**Comment by kirisanth1993** [comment]
Don't worry. We can fix it in simple way.

the first, fault we are doing is 
importing ApolloClient from '**apollo-boost**'. Actually we have to import **ApolloClient** from '**apollo-client**'.

    import ApolloClient from 'apollo-client';

Because, **ApolloClient** from **apollo-boost** only supports a smaller subset of configuration options. **ApolloClient** from **apollo-client** gives you all the configuration options.

then we can provide **link** and **cache** only to Apollo-client instance

    import { InMemoryCache } from "apollo-cache-inmemory";
    import { createHttpLink } from 'apollo-link-http';

    const client = new ApolloClient({ 
        link: new createHttpLink(
            {
                uri: "Your QraphQL Link"
            }
        ),
        cache: new InMemoryCache(),
    });

That's it

**Comment by StKostyantin** [comment]
> Don't worry. We can fix it in simple way.
> 
> 
> 
> the first, fault we are doing is 
> 
> importing ApolloClient from '**apollo-boost**'. Actually we have to import **ApolloClient** from '**apollo-client**'.
> 
> 
> 
>     import ApolloClient from 'apollo-client';
> 
> 
> 
> Because, **ApolloClient** from **apollo-boost** only supports a smaller subset of configuration options. **ApolloClient** from **apollo-client** gives you all the configuration options.
> 
> 
> 
> then we can provide **link** and **cache** only to Apollo-client instance
> 
> 
> 
>     import { InMemoryCache } from "apollo-cache-inmemory";
> 
>     import { createHttpLink } from 'apollo-link-http';
> 
> 
> 
>     const client = new ApolloClient({ 
> 
>         link: new createHttpLink(
> 
>             {
> 
>                 uri: "Your QraphQL Link"
> 
>             }
> 
>         ),
> 
>         cache: new InMemoryCache(),
> 
>     });
> 
> 
> 
> That's it

I know about it.
And use apollo-client.

my solution was to use nginx.  because my server is not written on Apollo Server, but on rust.  And for some reason, on a localhost in dev mode, I required Cors during requests.  I put the no-cors mod.  And that broke the ability to send a type / json request.  I’m already seen many this issues, and it’s not clear why the Apolo team will not fix this problem for devs on localhost and I have to install nginx.

**Comment by lukemiller** [comment]
A tidbit of info for others dealing with this error:

I was using the 'useGETForQueries' option in createHttpLink() which caused the error if a Fragment was missing.  Turning that off, solved the problem.

const link = createHttpLink({
  uri: endpoint,
  useGETForQueries: false
})

**Comment by david-golightly-leapyear** [comment]
I'm seeing this in some legitimate use cases that aren't fixable on the server, eg. when the front-end webserver (Traefik or nginx) times out a long request, or when the host is unreachable. The problem seems to come from [this code](https://github.com/apollographql/apollo-client/blob/d470c964db46728d8a5dfc63990859c550fa1656/src/link/http/parseAndCheckHttpResponse.ts#L12):

```ts
export function parseAndCheckHttpResponse(
  operations: Operation | Operation[],
) {
  return (response: Response) => response
    .text()
    .then(bodyText => {
      try {
        return JSON.parse(bodyText);
      } catch (err) {
        const parseError = err as ServerParseError;
        parseError.name = 'ServerParseError';
        parseError.response = response;
        parseError.statusCode = response.status;
        parseError.bodyText = bodyText;
        throw parseError;
      }
    })
```

A 504 Gateway Timeout may always return an HTML document. In this case, attempting to parse it as JSON results in the `err.message` property being set to `"Unexpected token < in JSON at position 0"`, which incorrectly masks the underlying issue.

Complicating this, `MockedProvider` by design does not invoke the typical Apollo Client code path (shown above), so we're not able to write unit tests for solutions eg. using Error Link. However, I was able to write a unit test by invoking the real `ApolloProvider` and my `ApolloClient` instance by mocking network requests via the excellent [nock](https://github.com/nock/nock) library:

```ts
import { ApolloProvider, gql, useQuery } from '@apollo/client'
import { render, waitFor } from '@testing-library/react'
import nock from 'nock'
import React from 'react'

import { apolloClient } from '.'

const mockQuery = gql`
  query foo {
    bar
  }
`

const TestComponent = () => {
  const { error } = useQuery(mockQuery)

  return <div data-testid="error-message">Error: {error?.message}</div>
}

const queryBody =
  '{"operationName":"foo","variables":{},"query":"query foo {\\n  bar\\n}\\n"}'

beforeEach(() => {
  nock.disableNetConnect()
})

afterEach(() => {
  nock.cleanAll()
  nock.enableNetConnect()
})

it('displays error messages when not JSON', async () => {
  // Allow localhost connections so we can test local routes and mock servers.
  nock.enableNetConnect('127.0.0.1')

  nock('http://localhost/')
    .post('/graphql', queryBody)
    .reply(504, '<table>Gateway timeout</table>')

  const { getByTestId } = render(
    <ApolloProvider client={apolloClient}>
      <TestComponent />
    </ApolloProvider>
  )

  await waitFor(() =>
    expect(getByTestId('error-message')).toHaveTextContent(
      'Error: <table>Gateway timeout</table>'
    )
  )
})
```

Of course, you will want to use `MockedProvider` for the vast majority of your Apollo components due to its ease of use, but I hope this method helps anyone struggling to fix this issue.

**Comment by ZowWeb** [comment]
Restarting my mac solved the issue ! 🤷🏻‍♂️ :man_shrugging:

**Comment by supernovaslc** [comment]
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { HttpLink } from 'apollo-link-http';
import { ApolloProvider } from 'react-apollo';
import { setContext } from 'apollo-link-context';

const isAuthenticated = sessionStorage.getItem('token');

const httpLink = new HttpLink({
  uri: 'http://localhost:3000/graphql',
});

const authLink = setContext((_, { headers }) => {
  const token = isAuthenticated;

  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : '',
    },
  };
});

const cache = new InMemoryCache();

const client = new ApolloClient({
  link: authLink.concat(httpLink),  
  cache
});

I got it fixed

**Comment by jdrydn** [comment]
Frequently happens when using [Cloudfront](https://aws.amazon.com/cloudfront) to:
- Serve both the frontend & backend
- Serve static HTML responses upon seeing a HTTP 502, 503 or 504 from the origin.

Fixed with the `customFetch` handler suggested by @jagonalez https://github.com/apollographql/apollo-feature-requests/issues/153#issuecomment-476832408 👍

**Comment by angad777** [comment]
This is still seems to be an issue with `"@apollo/client": "^3.3.16"` . 

Use a customFetch function as a workaround. 

```javascript
const customFetch = async (uri, options) => {
  const response = await fetch(uri, options)
  if (response.status >= 500) {
    // or handle 400 errors
    return Promise.reject(response.status)
  }
  return response
}
```

Example consumptions for nextjs with SSR/SSG/CSR: 

```javascript
function createApolloClient() {
  return new ApolloClient({
    ssrMode: typeof window === "undefined",
    link: new HttpLink({
      uri: "https://xyz.com/graphql", 
      headers: {
        Authorization: `Bearer ${jwt}`,
      },
      fetch: customFetch,
    }),
    cache: new InMemoryCache(),
  })
}
```

**Comment by alexkey89** [comment]
After struggling for 2 hours with this and nothing worked, for me it was as simple as adding www on the uri. Be sure that the "endpoint (path) for the GraphQL API on the site" is identical with the uri in apolloclient. ` uri: "https://www.my-site.com/graphql", `

**Comment by hwillson** [comment]
It doesn't look like there is a specific feature request here, so we'll close this off. Thanks!

**Comment by paulmelnikow** [comment]
The feature request is this: In the event of an unparseable JSON response, rather than emitting an unhandled exception (which is the current behavior) the error should propagate through the typical Apollo channels for response errors.

**Comment by david-golightly-leapyear** [comment]
@hwillson echoing @paulmelnikow, there is a specific feature request, though it's been buried under discussion of workarounds.

My comment here https://github.com/apollographql/apollo-feature-requests/issues/153#issuecomment-719098015 explains the source of the problem. @paulmelnikow explains the desired behavior. React-apollo should never throw a `Network error: Unexpected token < in JSON` error in response to 4xx/5xx status codes from the server, and should propagate the original error instead of masking it with this "unexpected token" error.

**Comment by daphnesmit** [comment]
SAD there is no way to formatError. If request never reaches a actual server the formatError in apollo-server makes  no sense so would need to be done on the client side.

**Comment by abbaty48** [comment]
After 2days of struggling with that issue on the android emulator with @apollo/client.
I use this solution, by typing this command in terminal Linux from  [https://stackoverflow.com/questions/49499250/react-native-android-debugger-connecting-to-10-0-2-2-instead-of-localhost](url) 
"adb -s emulator-5554 reverse tcp:3000 tcp:3000" without the [qoute], note also the 3000 is your graphql port
and change my URL to http://localhost:3000/graphql
