### ISSUE TITLE
@apollo/react-hooks: add option to useMutation for resetting the result returned by the tuple

### ISSUE THREAD

**Issue by n1ru4l** [apollographql/apollo-feature-requests#157]
In `@apollo/react-hooks` the `useMutation` hook returns a tuple with the result as a second argument. It would be helpful to have some way of resetting the result.

**Real World Use-Case:**

Show Modal based on `useMutation` result.

Example:

```tsx
const SubmitButton: React.FC<{}> = () => {
  const [mutate, { loading, data, resetMutationResult }] = useMutation(QUERY);

  return (
    <>
      <button onClick={() => mutate()}>Click me</button>
      {loading ? (
        <LoadingSpinner />
      ) : data ? (
        <Modal>
          {data.message}
          <button onClick={() => resetMutationResult()}>Close</button>
        </Modal>
      ) : null}
    </>
  );
};
```

When `resetMutationResult` is called `data` will be updated to undefined.

**Workaround:**

```tsx
const useMutationResultWithReset = <T extends {}>(
  data: T | undefined
): [T | undefined, () => void] => {
  const current = useRef(data);
  const latest = useRef(data);
  const [, setState] = useState(0);
  const clearCurrentData = () => {
    current.current = undefined;
    // force state update
    setState(state => state + 1);
  };

  if (data !== latest.current) {
    current.current = data;
    latest.current = data;
  }

  return [current.current, clearCurrentData];
};

const SubmitButton: React.FC<{}> = () => {
  const [mutate, { loading, data: _data }] = useMutation(QUERY);
  const [data, resetMutationresult] = useMutationResultWithReset(_data)

  return (
    <>
      <button onClick={() => mutate()}>Click me</button>
      {loading ? (
        <LoadingSpinner />
      ) : data ? (
        <Modal>
          {data.message}
          <button onClick={() => resetMutationResult()}>Close</button>
        </Modal>
      ) : null}
    </>
  );
};

```

**Comment by gajus** [comment]
Same here. Without this, you end up with additional `useState` just to observe if `useMutation` state.

**Comment by jannnik** [comment]
Same here. I use the result inside a dialog and need to reset it each time I re-open the dialog.

**Comment by n1ru4l** [comment]
@hwillson Would you consider merging a pull request from the community that implements this feature?

**Comment by neiker** [comment]
This will be useful on queries too.

Use case:
Reset the error when user press "close" on the modal showing the error. 

Now I have one extra state just to show/hide that modal, something like this:

```jsx
const [showError, setShowError] = React.useState(false);

  const [addCard, { data, loading, error }] = useMutation(ADD_CARD);

  useEffect(() => {
    if (error) {
      setShowError(true);
    }
  }, [error]);

...

return (
...
{showError && (<Modal
        title={error.title}
        body={error.message}
        onPressClose={() => setShowError(false)}
      />)}
...
);
```

**Comment by saernz** [comment]
Yeah having that functionality is definitely needed! I feel like I'm using minecraft redstone to implement workarounds :-P

Here's possibly another solution that works for me, and hopefully if I've done it right actually completely recreates the mutation object as well:

```javascript
const MutationProp = (props) => {
    const mutation = useMutation(ADD_CARD)
    const [mutFunc, mutState] = mutation
    useEffect(() => {
        props.setMutation(mutation)
    }, [mutState])
    return <div></div>
}

const SomeWrapper = () => {
    const [mutation, setMutation] = useState(null)
    const [resetCount, setResetCount] = useState(0)
    const loading = mutation ? mutation[1].loading : false
    const mutFunc = mutation ? mutation[0] : null

    return (
        <div>
            <MutationProp setMutation={setMutation} key={resetCount} />
            {loading && <LinearProgress variant="indeterminate" />}
            <div>
                {mutation && <SomeData mutation={mutation} />}
            </div>
            <Button onClick={() => {mutFunc()}} disabled={!!mutFunc}>Do Something</Button>
            <Button onClick={() => {setResetCount(curr => ++curr)}}>Reset</Button>
        </div>
    )
}

const SomeData = ({mutation}) => {
    const [doMutation, { data, error }] = mutation
    return (
        <div>
            {error && <p>Oh oh!</p>}
            {data && <p>Yay!</p>}
        </div>
    )
}

```

I pulled that out from my code and had to change some variable names and remove stuff so hope it still works. Basically works on the premise that changing the `key` of a component forces react to unmount and remount the component and since the useMutation hook is in there you also get a new mutation object. One con is you have to handle for a null when the component first initialises.

**Comment by danieldunderfelt** [comment]
Is this issue going anywhere? I would need this as well. The best solution I came up with is to configure my server to accept null as the upload parameter and return null as a response, but this is obviously not viable if you don't control the server or if changes like this aren't appropriate for your server.

Now I can just `upload(null)` to clear the upload data which works, but it would be great to have an officially supported way to do this in Apollo without requiring server-side support.

**Comment by n1ru4l** [comment]
@danieldunderfelt See my workaround in the OP

**Comment by philipbeber** [comment]
Note that if you just want to do something each time the mutate finishes, you can just wait on the promise that it returns, rather than use the hook. In fact you can use this to implement a much simpler workaround:

```js
const SubmitButton: React.FC<{}> = () => {
  const [mutate, { loading }] = useMutation(QUERY);
  const [data, setData] = React.useState(null);

  return (
    <>
      <button onClick={async () => setData((await mutate())?.data)}>Click me</button>
      {loading ? (
        <LoadingSpinner />
      ) : data ? (
        <Modal>
          {data.message}
          <button onClick={() => setData(null)}>Close</button>
        </Modal>
      ) : null}
    </>
  );
};
```

I kind of think this is better than the proposed solution. "Modal is open" is UI state that should be stored in the component, not in Apollo.

**Comment by n1ru4l** [comment]
@philipbeber Just don't forget to check whether the component is still mounted in such a case!

**Comment by neiker** [comment]
Agree with @n1ru4l 
Is better to use `onCompleted` option on useMutation
https://www.apollographql.com/docs/react/data/mutations/#options

**Comment by n1ru4l** [comment]
Or use effect with data as a dependency 😇

**Comment by neiker** [comment]
@n1ru4l I like to use onCompleted/onError. Looks a lot more clear for me.

**Comment by RobertMcReed** [comment]
Resetting mutations was added to @apollo/client 3.5.x https://github.com/apollographql/apollo-client/issues/8859#issuecomment-967332753
