### ISSUE TITLE
Add ability to set `partialRefetch` to true for all queries by default

### ISSUE THREAD

**Issue by camfletch** [apollographql/apollo-feature-requests#172]
`partialRefetch` should 100% be the default behavior. After writing to the cache, all queries should have the same behavior as if the component making the query was being freshly mounted (i.e cache miss, followed by a fetch), but without `partialRefetch` this is not the case.

We are worried about the risk of _not_ having the `partialRefetch` option set for every query, as we have a custom solution for syncing websocket updates to the Apollo Cache that can often result in partial data in a cache (and should absolutely trigger a fetch to hydrate the rest of that data).

Suggested solution would be to allow us to set overridden defaults for the arguments passed to a query (we are using the `useQuery` hook in our application). Or alternatively, to have `partialRefetch: true` as the new default (I understand the concerns about backwards compatibility, but I'm struggling to imagine a scenario where we _wouldn't_ want this as the default).

**Comment by MrLoh** [comment]
@camfletch can this not be set through the defaultOptions in the client? https://www.apollographql.com/docs/react/api/apollo-client/#example-defaultoptions-object

**Comment by camfletch** [comment]
Yep! My mistake I must have been looking at stale docs when I wrote this.

**Comment by moberegger** [comment]
@MrLoh The options in https://www.apollographql.com/docs/react/api/apollo-client/#ApolloClient.query doesn't list `partialRefetch` as a possible default option. Is that just something that was missed in the docs you think? 

@camfletch did this end up working for you?

The docs do say
> Provide this object to set application-wide default values for options you can provide to the watchQuery, query, and mutate functions. 

but I just don't know how to verify for sure whether the default `partialRefetch` option is being honoured or not.

**Comment by MrLoh** [comment]
Yep it works. Just not documented. Btw. reading souce code is the best way to answer such questions.

**Comment by moberegger** [comment]
I did try reading it but couldn't find where the default options were being applied. Got as far as https://github.com/apollographql/react-apollo/blob/master/packages/hooks/src/data/QueryData.ts#L51 and https://github.com/apollographql/react-apollo/blob/master/packages/hooks/src/data/QueryData.ts#L134, but didn't see any of the default options being reflected at that point, which is what prompted me to ask. I appreciate you answering so quickly!

I don't disagree that reading the source code can be a good way to get answers, but I disagree that it is the best way. The documentation exists so we don't have to read through source. I mean, why include documentation at all if it's truly better to just read the code? This is large and complex codebase that requires quite a bit of context, and I imagine it's not trivial to read for most people, least of all me.

**Comment by MrLoh** [comment]
Yeah. No question it should be documented. You could do a PR to the docs. I’m super busy at the moment, so I didn’t get around to it. I’m just always trying to encourage people to read the source code, it’s so helpful. But your right, this is hard to untangle here.

**Comment by moberegger** [comment]
> You could do a PR to the docs.

Right after your answer, I made a fork of Apollo to do just that actually! I will put one up soon-ish.
