### ISSUE TITLE
Execute function of useLazyQuery should resolve FetchResult

### ISSUE THREAD

**Issue by tz5514** [apollographql/apollo-feature-requests#174]
Hi, I just tried `useLazyQuery` for triggering query imperatively, and I found that the "execute function" would not resolve query result, but resolve with `undefined`.
This behavior make developer can't get query result by await the execute function. 

For example, if I want to imperatively trigger query in a `handleClick` function and instantly use this result to do some calculating or logic, we can't.

In addition, since `useMutation` has a similar returning API with `useLazyQuery` and Mutate function *will* resolve fetch result, and same on `refetch` function of `useQuery`.   I think `useLazyQuery` should has similar behavior. It **should** resolve with fetch result.

![image](https://user-images.githubusercontent.com/6021943/63088005-38254400-bf86-11e9-967b-5f1917bada00.png)

![image](https://user-images.githubusercontent.com/6021943/63088339-3b6cff80-bf87-11e9-89ea-d7e3ff55b605.png)

Thanks!

**Comment by jwld** [comment]
Yes please 🤞 Having to store the result in component state is a pita.

**Comment by andresg747** [comment]
Totally agree with this.
`useMutation` API is predictable enough. 
`useLazyQuery` has a very similar use case (speaking of imperative execution), and should have the same output type.

**Comment by srijanrana** [comment]
@tz5514 have you resolved this issue?

**Comment by tz5514** [comment]
@srijanrana no, still use `refetch` of `useQuery` to replace it now.

**Comment by aorielly** [comment]
`refetch` on `useQuery` is only helpful if you want to display the new data.  It is not helpful if you want to not call the query on page load, but you want to call it on a user method and do something with it immediately.

**Comment by hwillson** [comment]
We think the `useLazyQuery` execute function should return a Promise that resolves to the `FetchResult`; we're tracking that work here: https://github.com/apollographql/apollo-client/issues/7714
