### ISSUE TITLE
Feature request : support @argumentDefinitions directive

### ISSUE THREAD

**Issue by jacobwgillespie** [apollographql/apollo-feature-requests#18]
Migrated from: apollographql/apollo-client#2723

**Comment by axelhzf** [comment]
Any plan to implement this feature?

If I understand the problem correctly, it looks like relay transform this directive at compile time. This is why this could be hard to implement in apollo?

Posting this link as a reference:
https://github.com/facebook/graphql/issues/204

**Comment by Quramy** [comment]
It’s so interesting. I think we need “Fragment-scoped variables” when colocating query’s fragment and some UI components(e.g. React JSX).

So I’ve published https://github.com/Quramy/apollo-link-fragment-argument to enable `@argumentDefinitions` and `@arguments` directives.

Pls send me some feedbacks.

**Comment by mauriau** [comment]
How to use it on apollo-client for react ?
