### ISSUE TITLE
Mocking GraphQL responses incorrectly should show an error message, rather than return undefined

### ISSUE THREAD

**Issue by tntmarket** [apollographql/apollo-feature-requests#183]
I was mocking a [GraphQL query](https://www.apollographql.com/docs/react/development-testing/testing/), but specified an incorrectly typed response by accident.

The result was that `useQuery` returned `undefined` for `data`. After trimming down my test case to diagnose the problem, I realized that my incorrect mock was the culprit.

If `useQuery` failed early with a message like "Mock response doesn't match the GraphQL query", or if it was documented that `undefined` data means you mocked incorrectly, I'd save time diagnosing the issue.

Constructing an incorrect GraphQL query has the same consequence.

**Steps I took**

I started with a test that was a little more complex than this, and eventually trimmed it down to realize that my mocks were wrong:

```javascript
import { useQuery } from '@apollo/react-hooks';
import { MockedProvider } from '@apollo/react-testing';
import { mount } from 'enzyme';

import gql from 'graphql-tag';
import React from 'react';
import waitForExpect from 'wait-for-expect';

const GET_USER_QUERY = gql`
    query GetUser {
        user {
            name
        }
    }
`;

const User = () => {
    const { loading, data } = useQuery(GET_USER_QUERY);

    if (loading) return null;

    return <div>{data.user.name}</div>;
};

it('fetches user data', async () => {
    const view = mount(
        <MockedProvider
            mocks={[
                {
                    request: {
                        query: GET_USER_QUERY,
                    },
                    result: {
                        data: {
                            user: {
                                // typo
                                namee: 'Yolo Dolo',
                            },
                        },
                    },
                },
            ]}
            addTypename={false}
        >
            <User />
        </MockedProvider>,
    );

    await waitForExpect(() => {
        expect(view.text()).toContain('Yolo Dolo');
    });
});
```

The error was `TypeError: Cannot read property 'user' of undefined` when referencing `data.user.name`.

**Version**

```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 11.10.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 67.0.4
    Safari: 13.0.1
  npmPackages:
    @apollo/react-hooks: ^3.1.2 => 3.1.2
    @apollo/react-testing: ^3.1.2 => 3.1.2
    react-apollo: ^3.1.2 => 3.1.2
```

**Comment by jerelmiller** [comment]
Hey @tntmarket 👋 

We released an update in [v3.7.7](https://github.com/apollographql/apollo-client/releases/tag/v3.7.7) that will [log unmatched queries](https://github.com/apollographql/apollo-client/pull/10502) to the console. I'm going to go ahead and close this as completed.

Please ping us if you need any more help or open a new issue if there are further improvements you think can be made. Thanks!
