### ISSUE TITLE
useLazyQuery execute function should return a promise

### ISSUE THREAD

**Issue by ricick** [apollographql/apollo-feature-requests#190]
It would make sense if the useLazyQuery execute function returned a promise, in the same way as the useMutation execute function. Currently it returns void.

**Comment by dantehemerson** [comment]
Related with #174

**Comment by jerelmiller** [comment]
Hey @ricick 👋 

It looks like this feature was completed with https://github.com/apollographql/apollo-client/pull/8875. Please ping us if you need any more help. Thanks!
