### ISSUE TITLE
Support for delayed refetchQueries

### ISSUE THREAD

**Issue by Gerharddc** [apollographql/apollo-feature-requests#207]
I am in a situation where my GraphQL server is backed by a Postgres cluster with asynchronous replication to read replicas which means that sometimes there is a slight delay between when a write is performed and when it is reflected on reads. Together with this I have a few cases where I want changes to reflect to the user after a mutation but the queries are rather complex and writing proper optimistic updates does not feel worth the effort.  As far as I understand, the "refetchQueries" parameter on useMutation is supposed to help for such cases but unfortunately for me, instant refetching is just too fast at times.

It would be great if Apollo provided a way to specify a small delay on refetchQueries as this would solve my problems 99% of the time. I realise that the replication delay is variable and that a short refetch delay will not help every single time but it will still give a huge improvement with minimal effort to anyone in my position.

I am also aware that I can probably implement this behaviour manually using lazy queries but that would introduce extra effort and come with the same drawbacks so it would therefore be less preferred than natively adding delay support.

**Comment by hwillson** [comment]
You should be able to achieve this now with the new `onQueryUpdated` callback for mutations - see https://www.apollographql.com/docs/react/data/refetching/ for more details.

**Comment by enihar** [comment]
I have the latest React client version but still can't use `onQueryUpdated`

"@apollo/client": "^3.5.8"

This is the type definition

```
export interface BaseMutationOptions<TData = any, TVariables = OperationVariables> {
    variables?: TVariables;
    optimisticResponse?: TData | ((vars: TVariables) => TData);
    refetchQueries?: Array<string | PureQueryOptions> | RefetchQueriesFunction;
    awaitRefetchQueries?: boolean;
    errorPolicy?: ErrorPolicy;
    update?: MutationUpdaterFn<TData>;
    client?: ApolloClient<object>;
    notifyOnNetworkStatusChange?: boolean;
    context?: Context;
    onCompleted?: (data: TData) => void;
    onError?: (error: ApolloError) => void;
    fetchPolicy?: Extract<WatchQueryFetchPolicy, 'no-cache'>;
    ignoreResults?: boolean;
}
```

**Comment by dominicboston-kaluza** [comment]
Hey @midanosi 

Did you ever manage to get the `loading` state of the mutation to wait for the queries to be refetched. I find that the `loading` state returns `false` before the `delayRefetchedQuery` action has completed.

**Comment by midanosi** [comment]
> Hey @midanosi
> 
> Did you ever manage to get the `loading` state of the mutation to wait for the queries to be refetched. I find that the `loading` state returns `false` before the `delayRefetchedQuery` action has completed.

Hi, I'm afraid I didn't/don't remember. I left my job a couple weeks after the above post, and haven't used apollo since. Hope you figure out a solution!
