### ISSUE TITLE
Provide custom operationName to useQuery() and useMutation()

### ISSUE THREAD

**Issue by breathe** [apollographql/apollo-feature-requests#209]
I'd like to be able to provide a custom operationName to useQuery and useMutation()

I sometimes find myself wrapping `useQuery(...)` and `useMutation(...)` calls into application specific

`useDomainModel(...)`

methods -- which might then be used from more than one component.

I'd enforce that useDomainModel includes a 'callSite' parameter to identify something useful about the call-site.

I'd like to make use of this to construct a custom operationName -- or to at least be able to access the call-site parameter from a customFetch method like this:

```
const customFetch = (uri: string, options: any) => {
  const { operationName, callSite } = JSON.parse(options.body);
  return fetch(`${uri}/${operationName}/${callSite}`, options);
};
```

which would in my generate urls which identify both the operation name and the callsite:

like `/graphql/UseDomainModel-NavBar`.

This is for developer ergonomics.  I want to make the chrome network tools tab provide the most useful information to someone just joining the project to help them understand the app code.

Just imagine firing up a new project and seeing web requests like:

`token_api/graphql`
`token_api/graphql`
`token_api/graphql`
`token_api/graphql`

Vs

`token_api/graphql/UseDomainModel/NavBar`
`token_api/graphql/UseDomainModel2/UserInfo`
`token_api/graphql/UseDomainModel3/CompanyInfo`
`token_api/graphql/MutateDomainModel2/UserInfo`
...

**Comment by breathe** [comment]
Hmm ... I'm realizing maybe I can do this already

**Comment by breathe** [comment]
I'm able to make this work by doing this ...

```
const customFetch = (uri: string, options: any) => {
  const body = JSON.parse(options.body)
  const { operationName } = body;
  const {callSite} = body.variables
  return fetch(`${uri}/${operationName}/${callSite}`, options);
};
```

But i have to update my graphql server to accept the callSite query variable ...

**Comment by jerelmiller** [comment]
Hey @breathe 👋 

This is an interesting idea! While I appreciate the thought, your custom fetch solution and/or a custom [Apollo Link](https://www.apollographql.com/docs/react/api/link/introduction) should be enough to customize the request behavior you're looking to achieve. This feels like a very niche feature request and I'm not sure we can provide a generalized solution that makes sense for all users baked into the core of the client.

We have lots of interesting [community published links](https://www.apollographql.com/docs/react/api/link/community-links) so I'd definitely encourage you to consider creating your own if you feel there is enough value here.

Thanks for opening the request!
