### ISSUE TITLE
Request for new fetchPolicy: network-once

### ISSUE THREAD

**Issue by alexandrasmith00** [apollographql/apollo-feature-requests#215]
I am wondering if there are any plans to add additional fetch policies, namely one that makes the request whenever a page is refreshed.  For example, component loads, information is fetched and then stored in the cache for the session.  If user reloads browser window, the information would be refetched.  It behaves like network-only the first time, and then not again.

Is there a way to do this or any plans to add a new fetch policy?

**Comment by dylanwulf** [comment]
That's how `cache-first` works. The cache is always cleared when you reload the browser window, unless you're using a persisted cache
