### ISSUE TITLE
Improving Apollo's testing experience

### ISSUE THREAD

**Issue by klaaspieter** [apollographql/apollo-feature-requests#221]
## Introduction

A new Apollo link solely for testing purposes to allow for more finegrained control over what is mocked and when. And a way to automatically generate mock data for any operation.

Inspired by Relay: https://relay.dev/docs/en/testing-relay-components

## Motivation

`MockedProvider` works for simple cases, but providing mocks upfront can get complicated fast. Components at the leaves of the component tree tend to do a single query, but when testing components at the root one has to provide mocks for each component in the tree. It can be very hard to figure out which queries will be done. Even when that work is done the test remains fragile because a single query being added or changed can change the result of the test.

Then there is the problem of large nested queries. Generating data for these can be error prone and it can be hard to debug when fields are missing (https://github.com/apollographql/apollo-feature-requests/issues/115). I think the Relay documentation actually describes it best. Replace Relay with Apollo:

> One of the patterns you may see in the tests for Relay components: 95% of the test code, is the test preparation: the gigantic mock object with dummy data, manually created, or just a copy of a sample server response that needs to be passed as the network response. And rest 5% is actual test. As a result, people don't test much. It's hard to create and manage all these dummy payloads for different cases. Hence, writing tests are time-consuming and painful to maintain.
> — https://relay.dev/docs/en/testing-relay-components#testing-with-relay

Testing components with polling reliable is even near impossible. I have done some tests where extra mocks are provided. The results in the final mocks are then used to ensure that polling was stopped for example. Very roughly something like this:

```jsx
<MockedProvider mocks={[
  { data: { status: "Loading" } },
  { data: { status: "Ready" } },
  { error: "Should never happen"} 
]}>
  <Component pollInterval={1} />
</MockedProvider>

/* 
  Wait an arbitrary amount of time to ensure that we get to the ready state.
  There is no 100% guarantee that the error state is ever hit when `stopPolling` isn't called
  because it all depends on these timeouts.

  In other words it's possible this test succeeds even when `stopPolling` is never called. 
  One can add more waits, at the cost of slower tests.
*/
await wait()
await wait()
await wait()

expect(queryByText("Should never happen")).not.toBeInTheDocument()
```

## Proposed solution

A new Link: [`apollo-mock-link`](https://github.com/klaaspieter/apollo-mock-link). The link queues all operations and only resolves or rejects them when asked to do so. It can be combined with a [mock data generator](https://github.com/klaaspieter/fakeql) that automatically generates valid responses for each operation.

Let's look at an example of nested component that runs 3 queries. One for the current user `me`, one for all todos which have a `title` field and finally a query for all unresolved todos.

```jsx
const link = new MockLink()

const { getByText } = render(<MockedProvider link={link}><Component /></MockedProvider>)

expect(getByText("Loading…"))

// Return a response manually
link.resolveMostRecentOperation({ me: { name: "Hello" })

expect(getByText("Hello")).toBeInTheDocument()

// Return a generated response with default values for each field
link.resolveMostRecentOperation((operation) => fakeQL({ operation }))

expect(getByText(`mock-value-for-field-"title"`)).toBeInTheDocument()

// Return a generated response with the a specific `Todo.title`:
link.resolveMostRecentOperation((operation) => fakeQL({ 
  operation,
  resolvers: {
    Todo: { return { title: "Unresolved Todo" }} 
  }
}))

expect(getByText("Unresolved Todo")).toBeInTheDocument()
```

The above also works for polling which needs to stop after some sentinal value. Let's say we're polling for a `status` field to become `READY`:

```jsx
link.resolveMostRecentOperation({ status: "LOADING" })

expect(getByText("Loading")).toBeInTheDocument()

link.resolveMostRecentOperation({ status: "LOADING" })

expect(getByText("Loading")).toBeInTheDocument()

link.resolveMostRecentOperation({ status: "READY })

expect(getByText("Ready")).toBeInTheDocument()
expect(link.pendingOperations.count).toBe(0)
```

Note: Astute observers may realize that the above example need `wait`s because each query will be run on the next tick. These examples show _ideal_ usage. I hope to figure out and propose a solution for the (un)necessary `wait`s in tests in the future.

### Shallow rendering

One alternative for component trees with many queries is to shallow render components at the root. This works if the queries are in nested components. If the root itself however has all the queries the same problems arise. Granted this is probably not great API design but not something discouraged by Apollo's APIs.

### Manual mocks

The approach [described here](https://medium.com/free-code-camp/a-new-approach-to-mocking-graphql-data-1ef49de3d491) is mentioned often (also on this issue tracker). It however still requires making manual mocks for individual types in your schema. Large nested types are still hard to generate data for 

### Keep everything as is

The current `MockLink` already has the undocumented `addMockedResponse` method. An alternative could be to document that method. However it still requires mocking responses before they happen which has some flaws (https://github.com/apollographql/apollo-feature-requests/issues/206, https://github.com/apollographql/apollo-feature-requests/issues/173, https://github.com/apollographql/apollo-feature-requests/issues/115)

**Comment by insidewhy** [comment]
@klaaspieter It's actually pretty simple to implement a `MockLink` and pass it to the MockedProvider, the API you requested there could be written in just an hour or two.

Here's a `MockLink` I wrote that can be used to assert against the last request and also match requests with arbitrary variables and set up matches that can run more than once:

```typescript
// Copyright 2020 insidewhy, released under ISC license
import { MockLink, MockedResponse } from "@apollo/react-testing";
import { Operation, FetchResult, Observable } from "apollo-link";
import { addTypenameToDocument } from "apollo-utilities";
import { print, DocumentNode } from "graphql";

export interface WildcardMockedResponse extends MockedResponse {
  nMatches?: number;
}

interface StoredMock {
  result: FetchResult | (() => FetchResult) | undefined;
  // by default a mock will match an infinite number of requests
  nMatches: number;
}

/**
 * Extends MockLink to provide the ability to match request queries independent
 * of their variables and have them match 1 or more responses. Also stores the
 * last request for use in assertion frameworks.
 */
export class WildcardMockLink extends MockLink {
  private wildcardMatches = new Map<string, StoredMock[]>();
  public lastRequest?: {
    query: DocumentNode;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    variables: Record<string, any>;
  };

  request(op: Operation): Observable<FetchResult> | null {
    const mockKey = print(op.query);
    const storedMocks = this.wildcardMatches.get(mockKey);

    if (storedMocks) {
      this.lastRequest = {
        query: op.query,
        variables: op.variables,
      };

      const nextStoredMock = storedMocks[0];

      if (--nextStoredMock.nMatches === 0) {
        storedMocks.shift();
        if (!storedMocks.length) {
          this.wildcardMatches.delete(mockKey);
        }
      }

      return new Observable(observer => {
        const { result } = nextStoredMock;
        if (result) {
          setTimeout(() => {
            observer.next(typeof result === "function" ? result() : result);
            observer.complete();
          }, 0);
        }
      });
    } else {
      const response = super.request(op);
      this.lastRequest = {
        query: op.query,
        variables: op.variables,
      };
      return response;
    }
  }

  addWildcardMockedResponse(...responses: WildcardMockedResponse[]): void {
    responses.forEach(response => {
      const mockKey = this.buildCacheKey(response.request.query);
      const storedMocks = this.wildcardMatches.get(mockKey);
      const storedMock = {
        result: response.result,
        nMatches: response.nMatches || Number.POSITIVE_INFINITY,
      };
      if (storedMocks) {
        storedMocks.push(storedMock);
      } else {
        this.wildcardMatches.set(mockKey, [storedMock]);
      }
    });
  }

  removeWildcardMockedResponse(request: DocumentNode): void {
    this.wildcardMatches.delete(this.buildCacheKey(request));
  }

  private buildCacheKey(request: DocumentNode): string {
    return print(this.addTypename ? addTypenameToDocument(request) : request);
  }
}
```

**Comment by insidewhy** [comment]
Released this package which supports wildcards in mocks and a bunch of other nice functionality to help writing tests: https://github.com/insidewhy/wildcard-mock-link

I find that specifying requests ahead of time is acceptable, as long as you can make wildcard matches on the variables as this package supports. When it comes to subscriptions, it's very useful to send out responses using methods, so this package also supports that. It is documented and tested, and very happy to get feedback and add more functionality.

**Comment by klaaspieter** [comment]
@insidewhy That's awesome 🙏. In general I;m not a fan of the mock the world upfront it's definitely an improvement over what's there right now. I'm happy there are more people working on the same problem. For a while I was afraid it was just me experiencing these problems 😬

**Comment by insidewhy** [comment]
@klaaspieter I think I'll add a "match all requests" wildcard option, and then have methods for pushing out responses as needed. That should pretty much match your API request while also supporting scenarios where it's useful to mock up front.

**Comment by martdavidson** [comment]
Just piling on that testing needs some love - especially around firing subscription events manually with MockedProvider and the combination of mocking useQuery and useSubscription in the same MockedProvider.

@insidewhy I'll be checking out your package shortly to see if I can just use it as a drop in replacement.

**Comment by insidewhy** [comment]
@martdavidson It's fully compatible and lets you fire subscription events manually, other features too!
