### ISSUE TITLE
ApolloClient 3(Feature Request): makeLocalVar separated from cache

### ISSUE THREAD

**Issue by Banou26** [apollographql/apollo-feature-requests#222]
When using local variables in a real application, one big problem arise, you cannot make use of local variables in other files that defines type policies, e.g:

`cache.js`
```js
import typePolicies from './type-policies.js'

export default new InMemoryCache({
  typePolicies
})
```

`type-policies.js`
```js
import cache from './cache.js'

// at this moment, cache is undefined because of circular dependency
const localVariable = cache.makeLocalVar()

export default {
  Query: {
    myType: () => localVariable()
  }
}
```
<br><br>
One way to fix this would be to separate the variables store and the cache, e.g:

`variable-cache.js`
```js
export default new VariableCache()
```

`type-policies.js`
```js
import variableCache from './variable-cache.js'

const localVariable = variableCache.makeLocalVar()

export default {
  Query: {
    myType: () => localVariable()
  }
}
```

`cache.js`
```js
import localVariables from './variables.js'
import typePolicies from './type-policies.js'

export default new InMemoryCache({
  localVariables,
  typePolicies
})
```

**Comment by Banou26** [comment]
Right now a workaround is to add type policies dynamically after cache initialization, e.g:

`cache.js`
```js
export default new InMemoryCache({})
```

`type-policies.ts`
```js
import cache from './cache.ts'

cache.policies.addTypePolicies({
  Query: {
    myType: () => localVariable()
  }
})
```

**Comment by picosam** [comment]
@Banou26 what if your type policy depends upon your reactive var as well? I have this case where my `keyArgs` needs to access one of my cache reactive var values.

**Comment by Banou26** [comment]
I mean, in my case the type policy depends on the reactive var already, you can just call the reactive var in your keyArgs and it should work, since the type policy is added after the cache initialization the localVar should work fine.
