### ISSUE TITLE
Allow setting a "loading time" to MockedProvider

### ISSUE THREAD

**Issue by GuillaumeDesforges** [apollographql/apollo-feature-requests#239]
When working on my frontend, I want to be able to see the UI I have made for when the GraphQL query/mutation is loading to check it is done properly and the UX is good, or even just to show to my clients the UX in mocked mode.

For now I have to set breakpoints, but it is hardly usable.

An option to "delay" the MockedProvider response by a constant time (`responseDelay: 1000`) for all queries would help that.

**Comment by jpvajda** [comment]
https://github.com/apollographql/apollo-client/issues/9738

**Comment by jerelmiller** [comment]
Hey @GuillaumeDesforges 👋 

Unfortunately its not well documented but mocked responses accept a [`delay`](https://github.com/apollographql/apollo-client/blob/main/src/testing/core/mocking/mockLink.ts#L31) option that allows you to specify the number of milliseconds the mocked response should wait before "sending" that response. You can use it as such:

```ts
const mocks = [
  { 
    request: { query },
    result: { data: { ... } },
    delay: 100 // delay for 100ms
  }
]

<MockedProvider mocks={mocks}>
  {children}
</MockedProvider>
```

Does this address what you're looking for? I'll see if we can get this documented in our testing docs.

**Comment by GuillaumeDesforges** [comment]
Looks like it, thanks @jerelmiller :smile:

**Comment by jerelmiller** [comment]
Great to hear! I'm going to go ahead and close this. Thanks!
