### ISSUE TITLE
Suggestion: don't throw an exception on a cache miss

### ISSUE THREAD

**Issue by jamesreggio** [apollographql/apollo-feature-requests#24]
Migrated from: apollographql/apollo-client#2563

It's generally an antipattern to use exceptions for ordinary control flow. They're more difficult to reason about; they incur multiple expensive stackwalks throughout their lifecycle; and, most importantly, they're annoying as hell when debugging.

The final point is most relevant here. Many JavaScript app frameworks include top-level exception handlers, which then require you (as a developer) to break on all exceptions when debugging an issue. (The top-level handlers handle all exceptions, which makes breaking on unhandled exceptions useless.) Unfortunately, Apollo Client presently relies upon exceptions to signal cache misses, which can be quite noisy for these debugging scenarios.

**Comment by jerelmiller** [comment]
I believe this behavior is now old as cache misses do not result in exceptions thrown in the most recent versions of the client (3.8 at the time of this writing). As such, I'm going to go ahead and close this as completed.
