### ISSUE TITLE
Remove `esModulesInterop` from `tsconfig`

### ISSUE THREAD

**Issue by SimenB** [apollographql/apollo-feature-requests#248]
I'm currently attempting to update the types of `apollo-upload-client` to use `@apollo/client`: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46547. However, that PR is failing CI since `@apollo/client` uses ESM `import` of modules that only export CJS (e.g. `export =`).

I did start work on a PR, but using `import mod = require('mod');` fails with the following error:

![image](https://user-images.githubusercontent.com/1404810/89280180-896f8d00-d648-11ea-9f64-b54381e6bce0.png)

Not sure how to best reconcile this, or if it's even possible?

**Comment by jpvajda** [comment]
This seems resolved based on the state of the linked PR so I close it out.

**Comment by SimenB** [comment]
It only works due to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46191/files#diff-a08088df28748ca003a2e47e98a0ccc6f813fe4be56dc4c93a83e6c77bd9d665R19, which is not a good thing (it forces everybody downstream to use it as well)
