### ISSUE TITLE
Update Tutorial

### ISSUE THREAD

**Issue by jameskuizon13** [apollographql/apollo-feature-requests#249]
Hi. Is anyone already updating this [tutorial](https://www.apollographql.com/docs/tutorial/introduction/) from the official documentation? Can I help? If no one is doing it. I'll create some PRs and comment it here. So that anyone interested can review it. Is that fine? 

P.S. This is my first time trying to contribute. Thanks.

**Comment by jpvajda** [comment]
👋  I'm going to close this issue due to the age of this. This tutorial has been updated since 2020, but if you still have interest in contributing to our documentation or tutorials you can do that in the specific Github repository for each project. Thank you!
