### ISSUE TITLE
Provide log/message to indicate which incomplete data triggered a refetch

### ISSUE THREAD

**Issue by sirugh** [apollographql/apollo-feature-requests#254]
In upgrading to ACv3 we have noticed many "extra" network requests being made that aren't being made on ACv2. These tend to occur after a mutation that results in some data structure like removal from a list. At a glance it appears to be the result of some non-equal references within our cache, so admittedly it's possible that we are misconfiguring some type policies. That said, it would be great if ApolloClient could somehow inform us of which fields caused the refetch to occur. Even a verbose level console message would help. It would make debugging the misconfigured type policy much easier.

**Comment by jpvajda** [comment]
@sirugh If you can confirm this is still an issue for you or not that would be great. given the age of this issue, I'm going to close it out for now. However if you discover you are still experiencing the same problems, just let us know by reporting a bug in our [Apollo Client Project](https://github.com/apollographql/apollo-client/issues/new/choose). Thank you!
