### ISSUE TITLE
Docs TypeScript Examples.

### ISSUE THREAD

**Issue by wilo087** [apollographql/apollo-feature-requests#257]
It's too hard starting with GraphQL with all tools, libraries and framework.
In my case, I started trying to learn GraphQL using Apollo in the middle of React hooks, and the other variants like TypeScript.

Apollo has great documentation, but the examples are not too clear using JS and almost impossible to implement when you are new in TS, I recommend adding the examples using TypeScript and CS6 or higher.

I recommend create the Appllo's docs like [react-form-hook documentation] (https://react-hook-form.com/get-started)

**Comment by jpvajda** [comment]
Given the age of this issue, I'm going to close it out. We've made many documentation improvements with more getting started content since 2020, and are always open to suggestions.  If you feel there are still areas of improvement just let us know!
