### ISSUE TITLE
Some suggestions for this new section

### ISSUE THREAD

**Issue by smolinari** [apollographql/apollo-feature-requests#26]
Hi,

Not every suggestion is a feature request. Where should the other suggestions of improvement go? Maybe change this repo's name to "Suggestions" or "Ideas"?

There is no note of this new repo anywhere in the apollo-client repo at first glance. So, I'll bet any new contributors will be posting suggestions there, as is "normal" and the dev team be constantly chasing them to make their suggestions here. And I'll bet even if you make note of this in the README.md of the core repos, the devs will still falsely report suggestions in the core repos. Having to scold them into doing the right thing the next time, in the end, is unnecessary work and friction.

This "separation" of ideas from issues can be done smartly with [Github's labeling feature](https://help.github.com/articles/about-labels/) in the core repos. That is what labeling was meant to do. Yes, it means a little bit more work for the dev team to categorize and prioritize and filter issues to find what they are looking for. But in the end, it will be less work than trying to uphold the rule of having contributors go to a different repo to add their ideas. It's a poor change IMHO. Sorry..... :smile:

Scott

**Comment by hwillson** [comment]
Thanks for the feedback @smolinari!

The first sentence in this repo's [`README`](https://github.com/apollographql/apollo-feature-requests/blob/master/README.md) lists:

> This repository is used to track Apollo Client feature requests and discussions.

The idea being that the "dicussions" part covers "ideas". "Suggestions" are almost always "feature requests", but I'm happy to adjust the `README` if you feel anything isn't clear.

> There is no note of this new repo anywhere in the apollo-client repo at first glance. 

It's mentioned in multiple places in the `apollo-client` repo. It's one of the first lines in the new issue template, visible when you open a new issue. It's also mentioned in the [`CONTRIBUTING.md`](https://github.com/apollographql/apollo-client/blob/master/CONTRIBUTING.md#suggesting-features) doc and [`ISSUE_TRIAGE.md`](https://github.com/apollographql/apollo-client/blob/master/ISSUE_TRIAGE.md#feature-requests) doc. If you think it's missing anywhere else, please let us know.

> And I'll bet even if you make note of this in the README.md of the core repos, the devs will still falsely report suggestions in the core repos. Having to scold them into doing the right thing the next time, in the end, is unnecessary work and friction.

We won't be scolding anyone! 😄 We'll be politely asking them to open their FR in the new repo. 

> This "separation" of ideas from issues can be done smartly with Github's labeling feature in the core repos. That is what labeling was meant to do. 

Labeling is useful and we use it extensively, but (speaking from experience) it is not the be all / end all when it comes to managing issues and feature requests. Just look at what has happened to [other popular repos](https://github.com/npm/npm) that have relied on using labels to track issues, feature requests, ideas, suggestions, etc. Putting that aside though there is a bigger picture here that isn't quite ready to be discussed yet. Long story short, we see tremendous value in keeping the main `apollo-client` repo's issues focused solely on bugs. We're starting to clamp down hard on outstanding bugs, and want to get all of our feature requests organized for the design phase of Apollo Client 3. Also, this isn't the first time we've followed this approach. We've done it with other repos in the past, and it has worked out amazingly well.

> Yes, it means a little bit more work for the dev team to categorize and prioritize and filter issues to find what they are looking for. But in the end, it will be less work than trying to uphold the rule of having contributors go to a different repo to add their ideas. 

I respectfully disagree with this. The amount of work involved with getting people to open up feature requests in a new repo is almost nothing, on either side of the fence. The benefits that come from tracking bugs and feature requests in isolation however, are numerous.

> It's a poor change IMHO. Sorry..... 😄

No need to say sorry! We 💯% welcome all feedback, in any form. We're making these changes to help push Apollo Client forward and couldn't do any of this without community involvement, feedback, and support. Thanks again for your comments!

**Comment by hwillson** [comment]
One quick thing to add @smolinari - please stick with us while we make this transition. I strongly feel that over the next little while, you'll start to see the direct benefit doing this has had on Apollo Client's robustness, capabilities, and direction.

**Comment by jerelmiller** [comment]
Hey there 👋 

I'm doing a quick sweep of some of our old issues in this repo and came across this one. Seeing as this has been 5 years since this issue was opened, I'm going to go ahead and close this. By all means, feel free to open a new issue with any suggestions/ideas to make this better for our users. Thanks!
