### ISSUE TITLE
Allow SchemaLink.Options.schema as async function

### ISSUE THREAD

**Issue by RishikeshDarandale** [apollographql/apollo-feature-requests#264]
# Allow `SchemaLink.Options.schema` as async function

I am using [type-graphql][1] with apollo server and for SSR apollo client I want to use it `SchemaLink`. `type-graphql` gives a `async` method to create the schema as below:

```
const schema = await buildSchema({
  resolvers: [FirstResolver, SecondResolver],
});
```

If `schema` can alternatively provide a way to accept the async function which returns the graphql schema, then schemalink can be created as below:

```
const graphqlClient = new ApolloClient({
  ssrMode: true,
  cache: new InMemoryCache(),
  link: new SchemaLink({ schema: async () =>  { return await buildSchema({
  resolvers: [FirstResolver, SecondResolver],
})}})
});
```

So, can we allow it as below?

```
export namespace SchemaLink {
  export type ResolverContext = Record<string, any>;
  export type SchemaFunction = ( ) => GraphQLSchema | PromiseLike<GraphQLSchema>;
  export type ResolverContextFunction = (
    operation: Operation,
  ) => ResolverContext | PromiseLike<ResolverContext>;

  export interface Options {
    /**
     * The schema to generate responses from.
     */
    schema: GraphQLSchema | SchemaFunction;

    /**
     * The root value to use when generating responses.
     */
    rootValue?: any;

    /**
     * A context to provide to resolvers declared within the schema.
     */
    context?: ResolverContext | ResolverContextFunction;
  }
}
```

[1]: https://github.com/MichalLytek/type-graphql

**Comment by trevor-scheer** [comment]
In case this is helpful, Apollo Server supports the async construction of a schema object in a not-so-obvious way using the `gateway` option. Some details available [in the migration guide](https://www.apollographql.com/docs/apollo-server/migration#executor) but better examples available in the source via our tests. It's not well-documented as it's not a very common request, but it is possible.

**Comment by jerelmiller** [comment]
Hey @RishikeshDarandale 👋 

We have shifted this repo to be specific to the [Apollo TypeScript Client](https://github.com/apollographql/apollo-client). As such, I'm going to go ahead and close this issue.

If you're still in need of assistance or would like to raise this request again, please open an issue in the [Apollo Server repo](https://github.com/apollographql/apollo-server). Thanks!
