### ISSUE TITLE
Don't add __typename for non-normalized types (or have option to disable __typename per type)

### ISSUE THREAD

**Issue by eddiew** [apollographql/apollo-feature-requests#278]
I'm running apollo-client against a postgraphile server, where time interval types are returned as an object with `{ hours, minutes, ...etc }` subfields. I would like to use these objects directly with luxon's `DateTime.plus()` function, but luxon complains that it does not recognize `__typename` as a unit of time.

In many cases it's probably safe to omit `__typename` from non normalized types, although I'm not sure that this is always the case. Perhaps an option to disable it per-type would make sense.

**Comment by brainkim** [comment]
Probably a duplicate of https://github.com/apollographql/apollo-feature-requests/issues/6. Closing for housekeeping purposes. Let me know if you think it’s not a duplicate and why!
