### ISSUE TITLE
Unhandled Rejection (Error): Failed to fetch

### ISSUE THREAD

**Issue by pranay999000** [apollographql/apollo-feature-requests#280]
### While trying to fetch data from GraphQL I'm getting the following error.
![Screenshot 2021-01-14 154247](https://user-images.githubusercontent.com/35093184/104577197-32ea8e00-567f-11eb-8f1e-61e58f68bf78.png)

### My code looks like:

client
&emsp;.query({
&emsp;&emsp;query: gql\`
&emsp;&emsp;&emsp;query GetBook {
&emsp;&emsp;&emsp;&emsp;book(id: "5ffeed033c7c03240c2f03f1") {
&emsp;&emsp;&emsp;&emsp;&emsp;name
&emsp;&emsp;&emsp;&emsp;&emsp;genre
&emsp;&emsp;&emsp;&emsp;}
&emsp;&emsp;&emsp;}
&emsp;&emsp;`
&emsp;})
&emsp;.then(result => console.log(result));

function App() {
&emsp;return (
&emsp;&emsp;&lt;ApolloProvider client={client}>
&emsp;&emsp;&emsp;My first Apollo app
&emsp;&emsp;&lt;/ApolloProvider>
&emsp;);
}

ReactDOM.render(
&emsp;&lt;React.StrictMode>
&emsp;&emsp;&lt;App />
&emsp;&lt;/React.StrictMode>,
&emsp;document.getElementById('root')
);

**Comment by KevinEverywhere** [comment]
Why was this closed? I am still having this same issue in July 2021. Links for solutions?

**Comment by deepakbhattmits** [comment]
@KevinEverywhere,

 Yes I also have the same issue no luck. could you please Provide me some links or solution for the same.

**Comment by KevinEverywhere** [comment]
I no longer have access to the code, @deepakbhattmits, but I believe that I had to go about the resolution in a completely different way than I had anticipated. This issue was not resolved for my use case; and if I recall, the workaround was at a level above. Sorry that I don't have more information at my fingertips.
