### ISSUE TITLE
Make behavior of undefined in field policies consistent for keyArgs and keyArgsFunction

### ISSUE THREAD

**Issue by mwahlhuetter** [apollographql/apollo-feature-requests#295]
When not declaring the `keyArgs`, the field key is generated through the `storeKeyNameFromField` function using all argumens and variables, as far as i have seen in the source code.

If a function is used for keyArgs instead and `undefined` is returned, it is treated the same as if `false` is returned, because it checks for falsy values, and thus just creates a single field key from the field name without any arguments.

It would be nice to be able to create a specialized field key for some queries, and for all the others just use the query arguments and variables, so you don't have to return an array with all possible arguments that could be in the query.

Lets say I have a field policy like this for example

```ts
typePolicies: {
  Query: {
    fields: {
      order_lines: {
        keyArgs (args, context) {
          if (context.field?.alias?.value === 'orderDrafts') return context.field.alias.value
          if (context.args?.offset?) return 'ordersOverview'
          // for all other cases I just want to use the default behavior as if keyArgs would be undefined
          return undefined // is treated the same as false currently
        },
        merge...
      }
    }
  }
}
```

I have not found a way to create a keyArgs functions as I described above, and also have not found anything related in the docs, so I don't think this is currently possible. If I'm wrong or this approach would break some existing behaviors, I'm sorry in advance.

**Comment by jpvajda** [comment]
Thank you for reporting this! I suggest posting this in our [Apollo Community](https://community.apollographql.com/) for guidance from other Apollo users, as other's may have input into your question.

**Comment by mwahlhuetter** [comment]
For anyone stumbling upon this wanting the same behavior I described, I solved it with just returning 
```
keyArgs (args, context) {
  ...
  return args ? Object.keys(args) : undefined
}
```
