### ISSUE TITLE
Should docs for the react-apollo mutations utilize functional components?

### ISSUE THREAD

**Issue by chrisfosterelli** [apollographql/apollo-feature-requests#31]
Migrated from: apollographql/apollo-client#3414

**Comment by jerelmiller** [comment]
Hey there 👋 

I am doing a sweep through some old issues and came across this one. We are all in on the hooks API at this point and will be deprecating the query components in the future. The documentation currently reflects the hooks API as the default, so I'm going to go ahead and close this out. Thanks!
