### ISSUE TITLE
Ability to run `update` without optimisticResponse object

### ISSUE THREAD

**Issue by LydiaF** [apollographql/apollo-feature-requests#311]
Dear Apollo,

I would like to be able to run the update function without providing an optimisticResponse object.

At the moment I am working around it by just providing: `optimisticResponse: {}`.

The reason I would like this is because I have made functions that handle the fetch result in the cache, that don't require the proper optimisticResponse object.

Thanks for considering,

Lydia

**Comment by jpvajda** [comment]
Thank you for reporting this! I suggest posting this in our [Apollo Community](https://community.apollographql.com/) for guidance from other Apollo users, as other's may have input into your question.
