### ISSUE TITLE
Apollo Client 3.0 Roadmap

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-feature-requests#33]
~~Hi all! Once summer vacations are out of the way, we'll be hashing out the Apollo Client 3 roadmap. We have an approximate idea of the new features / functionality we want to get in place for AC 3 (based on open feature requests from the community, breaking changes required to work with new versions of 3rd party libraries, and a few additional ideas of our own). Once we have a draft of the v3 roadmap ready, we'll share it here for feedback. It's going to be an exciting release!~~ 🚀 

**UPDATE (2020-04-27):** The most up to date roadmap can be found [here](https://github.com/apollographql/apollo-client/blob/master/ROADMAP.md). We're aiming for an AC 3 RC in May 2020.

**Comment by joshribakoff** [comment]
I am in suspense 😉

**Comment by danilobuerger** [comment]
@hwillson If v3 is breaking anyway (looking at semver), it would be really nice to consider moving query and mutate to return `Observable` instead of `Promise`. This would then allow easy cancellation for example in react components. 

See https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html https://medium.com/@benlesh/promise-cancellation-is-dead-long-live-promise-cancellation-c6601f1f5082

**Comment by mbrowne** [comment]
Is the in-development v3 code being committed publicly on github somewhere? Or all still behind the scenes at this point?

**Comment by hwillson** [comment]
Hi all - sorry for the delay on this. We've been bouncing around a lot of different ideas, and have been considering several different approaches to Apollo Client 3 (and how it will fit within other changes/updates coming in the Apollo ecosystem). Long story short, we have an initial plan of attack ready for Apollo Client 3.

**Note:** We're actually hoping to split things up a bit, so we can get some of the non-breaking features out sooner than later (in a 2.x release). All of the functionality listed below will be in Apollo Client 3, but🤞some of it will be available sooner.

## Features

At a high-level, the big ticket Apollo Client 3 items that we're planning on addressing are:

**1. Building cache invalidation / deletion / garbage collection capabilities into core.**

* This is hands down the most requested outstanding feature.
* Main related issues: https://github.com/apollographql/apollo-client/issues/621 and https://github.com/apollographql/apollo-feature-requests/issues/4

**2. Bringing apollo-link-state capabilities into core.**

* [`apollo-link-state`](https://github.com/apollographql/apollo-link-state) will no longer be a separate package. It will be adjusted/refactored/merged into Apollo Client, and it will become part of the Apollo Client public API.
* Many of the existing issues outlined [here](https://github.com/apollographql/apollo-link-state/issues?q=is%3Aissue+is%3Aopen+label%3Aroad-to-1.0) will be addressed at the same time.
* We're hoping to have some of this work completed and released a bit earlier, in Apollo Client 2.x.

**3. Merging apollo-boost into core.**

* Apollo Boost does a great job at getting people up and running with Apollo Client quickly, using sensible defaults. 
* Unfortunately, presenting 2 ways of using Apollo Client, via `apollo-client` or `apollo-boost`, has led to a fair amount of confusion among users.
* The Apollo Boost project will be retired, and all existing functionality will be made available via Apollo Client itself. This means `apollo-client` will provide a quick getting started (minimum config) approach, that can be overridden with additional config elements as needed.
* We're hoping to have some of this work completed and released a bit earlier, in Apollo Client 2.x.

**4. Address many (hopefully all) of the outstanding refetch related issues.**

* Refetching and having data disappear because of differences between incoming data and data in the cache, is a long standing issue.
* There are technical reasons why this is happening, and available workarounds that help mitigate this problem (like using Apollo Client's `mutate` `update` function to merge results and cache entries manually, or using React Apollo's `partialRefetch` option to refetch when a discrepancy is found).
* That being said, this has been a large area of frustration for many users. We will be looking into a new approach for handling refetching that helps avoid these discrepancies.
* Related issues (just a sampling - there are many more):
    * https://github.com/apollographql/apollo-client/issues/3267
    * https://github.com/apollographql/apollo-client/issues/3468
    * https://github.com/apollographql/apollo-client/issues/2920
    * https://github.com/apollographql/apollo-client/issues/2847

**5. Focus on getting bundle sizes down.**

* The `apollo-client` bundle size will be reduced - full stop.

**6. Address issues / PR's / outstanding code changes that we've flagged as breaking.**

* This list it still being worked on. TBD.

## Design

Design work is underway, and detailed designs will be shared in separate issues, for feedback. 

## Timeline

We're aiming to have this work done as soon as possible! 🙂 

## Related Work

Since Apollo Client and React Apollo are closely related, React Apollo will be bumped to 3.0 when Apollo Client 3.0 is released. Any outstanding React Apollo breaking changes will be included in this release, as will updates required to align React Apollo more closely with upcoming React changes (like React Suspense).

Thanks all - let me know if you have any questions/comments. 🚀

**Comment by green-pickle** [comment]
@JoviDeCroock you're not wrong, from the above roadmap core will have more things you never need (like apollo state or apollo boost, which will also bring their dependencies), hope tree-shaking will remove them (it won't).

We can thank devs who can't read the docs. Same thing happened with apollo-server 2 where separate middlewares were removed and combined into an unusable monster just because newbies couldn't combine two functions.

Let's also hope HOCs won't be removed from react-apollo.

Enjoy 😉

**Comment by joshribakoff** [comment]
@jovidecrook the point is they are consolidating packages. Peer dependencies are when you have separate packages, e.g. React is a peer dependency of react-Apollo. 

@green-pickle what build tool are you using that has tree shaking but still bundles modules you don't import? If you don't import it, it won't be bundled. That's not even tree shaking that's just basic bundling. Tree shaking will remove code you did import but didn't use. I am a dev who reads the docs and this is my understanding of tree shaking. Your comment comes off a bit negative and based on my knowledge of tree shaking it seems inaccurate

**Comment by JoviDeCroock** [comment]
@joshribakoff Yes but an internal zero-config can't really be seen as a peer dependency in my opinion. These will be imported and will be used in the internal code so will always be included in the bundle and will be used in the internal code making tree shaking irrelevant.

**Comment by jbaxleyiii** [comment]
@green-pickle @JoviDeCroock There is definitely a balancing act between bundle size and features here that we need to manage, but after some investigation, we think there is a lot of straight up code removal that we can do which will make a big difference. In making a lot of composable parts, one of the trade offs is the desire for abstract components that carry extra weight of open interop we can remove.

With @benjamn  and @hwillson on the case, I'm super optimistic about having both a great getting started experience and a production sized client :)

Also @green-pickle I think you'll be happy with some upcoming changes on the server. We hear you loud and clear about some missteps there and will have changes soon that I hope you will love

**Comment by danilobuerger** [comment]
@jbaxleyiii is there a roadmap for apollo-server ?

**Comment by jbaxleyiii** [comment]
@danilobuerger 🔜 🔜 🔜

**Comment by danilobuerger** [comment]
@jbaxleyiii maybe you could already create a skeleton issue for that, like @hwillson did here, so we can subscribe and get notified once the roadmap stands? that would be awesome!

**Comment by JoviDeCroock** [comment]
@jbaxleyiii Thanks for the information. I'm looking forward to it!

**Comment by joshribakoff** [comment]
@jovidecroock consolidating packages does not necessarily mean they're going to couple them like that

**Comment by haytko** [comment]
🙂 really interested to see how 1 shakes out

**Comment by Elfayer** [comment]
Will there be a migration script/documentation for people starting a project recently with the current AC version?

**Comment by koresar** [comment]
Would be also very good to see similar roadmap for the Apollo server. It much needed there.

**Comment by archSeer** [comment]
I would love to see #2 on the v3 roadmap as well -- it's kind of tedious to have to manually parse dates/datetimes in every component

**Comment by gregwym** [comment]
Agree with @archSeer. GraphQL server have mature support for custom scalar type for long.

**Comment by edslocomb** [comment]
Anyone else interested in improved test tooling/docs?

I dunno about other projects out there, but for ones I work on it sure would be nice if we could easily stub queries/responses and use them to test subsystems of components linked via Apollo...

**Comment by spyshower** [comment]
> Anyone else interested in improved test tooling/docs?

Hell yes!

**Comment by Matfork** [comment]
> @hwillson If v3 is breaking anyway (looking at semver), it would be really nice to consider moving query and mutate to return `Observable` instead of `Promise`. This would then allow easy cancellation for example in react components.
> 
> See https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html https://medium.com/@benlesh/promise-cancellation-is-dead-long-live-promise-cancellation-c6601f1f5082

I think this could be a great feature. Using observables or a way to cancel ongoing promises. It seems v3 will bring a bunch of good stuff.

**Comment by geekox86** [comment]
Greetings gentlemen. Outstanding work, thank you!

Where can we watch the progress of this upcoming major release? Any updated plans/dates or feature list?

**Comment by benseitz** [comment]
@geekox86  Do you follow https://github.com/apollographql/react-apollo/pull/2892?

**Comment by programisti** [comment]
I think this package should be default on Apollo 3.0
https://github.com/trojanowski/react-apollo-hooks

**Comment by hwillson** [comment]
@programisti Please see https://github.com/apollographql/react-apollo/pull/2892. React Apollo 3 will have hooks baked in.

**Comment by hwillson** [comment]
Hi all - we've just published a new iteration of the Apollo Client 3 roadmap here:

https://github.com/apollographql/apollo-client/blob/master/ROADMAP.md

Work is well underway, and we should have an RC ready towards the end of October. Thanks!

**Comment by UpsidePotential** [comment]
I hope I am not reading too much into the roadmap. Seems like React is going to be first class.  Are you going to continue to support other frameworks such as Angular?

**Comment by hwillson** [comment]
@UpsidePotential The React Apollo project is being merged into Apollo Client to help reduce the maintenance overhead that comes from managing these projects separately, and to give us a way to provide a better out of the box getting started experience. We're definitely still going to support other view integrations, and will outline ways to use the Apollo Client 3 package without bringing in any of the extra React weight, if it's not needed.

**Comment by jbaxleyiii** [comment]
@UpsidePotential to further what @hwillson has said, the React integration has always been at a higher level of support after I joined the company since it was no long "community maintained". We are moving it in like @hwillson said to ease our maintenance burden but Apollo Client is, will, and will always be usable by any view layer or none at all ❤️

**Comment by geekox86** [comment]
Greetings gentlemen,

Thank you for all the good work.

I suggest to keep the react integration as optional one like `@apollo-client/apollo-react`

Also the docs for the code vanilla apollo-client needs to be enhanced with examples that are just vanilla JS (no react or view integration layer).

**Comment by seanharr11** [comment]
Thanks for all the great work fellahs! This is such a great tool.

I think if Apollo is going to address #1 then it'd make sense to do so now, or close the issue (and crush my hopes and dreams). 

We would break interface of those relying on an exception getting thrown if a query DNE in the cache (which we can justify in a major release).

IMO we would address a class of runtime bugs produced when a query's cache is read from before the query has ever been run. In practice this occurs quite often (_can speak from experience!_)

**Comment by adamtysonsmith** [comment]
Is the 3.0 documentation available anywhere yet?

**Comment by levrik** [comment]
@adamtysonsmith Looks like it's available here: https://www.apollographql.com/docs/react/v3.0-beta

**Comment by morrys** [comment]
Hi guys,
I would like to propose you to export the function [markMutationResult](https://github.com/apollographql/apollo-client/blob/release-3.0/src/core/QueryManager.ts#L1439) and to be able to use the function [ generateUpdateQueriesInfo](https://github.com/apollographql/apollo-client/blob/release-3.0/src/core/QueryManager.ts#L179) through the QueryManager.

These changes allow easier integration into [the library](https://morrys.github.io/wora/docs/apollo-offline) that I created for Apollo offline capabilities.

In apollo-client 2.x.x they were accessible through the client store.

if you are interested, let me know so I will be able to offer you a PR, as soon as I can.

Thanks,
Lorenzo

**Comment by thojanssens** [comment]
Hello 👋 can the roadmap be updated?
It says Completion date: Full RC available end of October 2019
But it's still in beta if I'm not wrong.

**Comment by SimenB** [comment]
https://github.com/apollographql/apollo-client/pull/5116#issuecomment-571700822

**Comment by Deelux** [comment]
Any news on when Apollo 3.0 will be released?

**Comment by hwillson** [comment]
@Deelux we've very close to moving to an RC. There are a few remaining pieces of functionality we want to get into place before doing that, and we still have a good chunk of docs work to finish up. We can't share a definitive launch date yet (as every time I do I'm wrong 🙂), but you can try things out today using `@apollo/client@beta`. We're using the `beta` in production ourselves and it's working well for us.

**Comment by Deelux** [comment]
@hwillson Anything I can do to help?

**Comment by hwillson** [comment]
@Deelux at this point testing out the `beta` and reporting any issues you find would be a big help. Thanks!

**Comment by klaussner** [comment]
Given that caching improvements are an important part of the next release, would you be open to considering https://github.com/apollographql/apollo-client/issues/4141 for 3.0 as well (see [my comment in the issue thread](https://github.com/apollographql/apollo-client/issues/4141#issuecomment-596215752) for details)?

**Comment by oshalygin** [comment]
One of the biggest pain points right with the beta is that you can't disable the cache like you could with the previous release @hwillson 

https://github.com/apollographql/apollo-feature-requests/issues/91

Curious on your thoughts if this can be introduced in a future release or if its going to be part of RC?

**Comment by markwain** [comment]
> @Deelux at this point testing out the `beta` and reporting any issues you find would be a big help. Thanks!

@Deelux seems like beta40 is breaking devtools (works fine on beta39)
https://github.com/apollographql/apollo-client-devtools/issues/250

**Comment by kritijain2269** [comment]
Any news on when Apollo 3.0 will be released?

**Comment by SimenB** [comment]
https://github.com/apollographql/apollo-client/commit/0f210391ed9bb0d51dac948f65eb48516f64ecf8

**Comment by sahand-javid-csod** [comment]
How far are we from Stable version for v3? Should we start using rc0 for production?

**Comment by jainnirmal1992** [comment]
Any news on when Apollo 3.0 will be released?

**Comment by hwillson** [comment]
This was done!

**Comment by mnpenner** [comment]
Oh yeah.. looks like it was released about 8 months ago. [Changelog](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-300)
