### ISSUE TITLE
Support Request: Is there a way to use cache-first policy with a TTL? 

### ISSUE THREAD

**Issue by awm086** [apollographql/apollo-feature-requests#330]
I'm an Apollo newbie here so forgive my ignorance.
I am looking the the apolloClient fetch policy and it indicate that using `cache-first` fetch policy prioritize serving query results from cache. So: 

1. Does this mean it will not be invalidated until the user does so?
2. Is there a way to set the fetch policy to be `cache-first` and invalidate cache objects (query results) after a TTL (some time) has elapsed?

**Comment by jpvajda** [comment]
Thank you for reporting this! I suggest posting this in our [Apollo Community](https://community.apollographql.com/) for guidance from other Apollo users, as other's may have input into your question.

This repo is for feature requests only so I'm going to close this out.
