### ISSUE TITLE
Make Apollo client not having React as peer dep

### ISSUE THREAD

**Issue by ahnpnl** [apollographql/apollo-feature-requests#333]
## Problem

When installing Apollo client with some other UI  libraries/frameworks other than React, package manager often complains about React dep not available.

## Proposal 

It would be much better if Apollo client is framework agnostic and put stuffs related to React into a different npm package.

## Notes

I believe this request might be duplicated with other previous similar requests. Please consider it 🙏

**Comment by jerelmiller** [comment]
This work has been completed in https://github.com/apollographql/apollo-client/pull/9940 and will be released along with v4.

v4 is still a ways off, but we can at least mark this as completed. Thanks for raising the issue!
