### ISSUE TITLE
Support Queries that dont return an html element and can save to a variable

### ISSUE THREAD

**Issue by bhaktatejas922** [apollographql/apollo-feature-requests#345]
It's something thats really basic that I don't understand why it doesnt exist already. Asides from it being the "right" or wrong way to do things, some use cases need to be done this way and doing a bunch of hacks to do it kind of sucks

**Comment by jerelmiller** [comment]
Hey @bhaktatejas922! Thanks for filing the request.

Would you mind going into a bit more detail and perhaps providing an example? I'm a bit confused as to what you're looking for. Queries typically return JSON data so I'm not entirely sure where the HTML element you're referring to is coming from.

An example would go a long way for us to help us figure out how to make Apollo Client better!
