### ISSUE TITLE
useLazyQuery's refetch method allows updating variables but should also allow updating the query without having to remount the component it's used in

### ISSUE THREAD

**Issue by atomless** [apollographql/apollo-feature-requests#352]
It's an odd omission to not be able to update the gql query when calling the reFetch method returned by useLazyQuery. This forces us to trigger a complete remounting of the component in which it's used just to update the query. You can override the variables, so why not the query?

**Versions**
@apollo/client: 3.5.10
graphql: 16.0.1
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 99.0.4844.83 (Official Build) (x86_64)

**Comment by jerelmiller** [comment]
Hey @atomless 👋 

This functionality was [added](https://github.com/apollographql/apollo-client/pull/10698) in [v3.7.11](https://github.com/apollographql/apollo-client/releases/tag/v3.7.11). You can call the execute function returned from `useLazyQuery` to update the query document.

```tsx
const [execute] = useLazyQuery(document)

// will execute the query using `newDocument` instead
execute({ query: newDocument });
```

Hope this helps!
