### ISSUE TITLE
Provide httpCache() overload that accepts File producer lambda for directory to avoid File IO on main thread

### ISSUE THREAD

**Issue by mhernand40** [apollographql/apollo-feature-requests#353]
In my team's Android project, we are leveraging the `ApolloClient.Builder.httpCache` extension. However, because the `File` is required upfront, our app is immediately running into a `DiskReadViolation` during app launch.

Take the following Dagger 2 provider function for providing the `ApolloClient` in the Dependency graph:
```Kotlin
    @Singleton
    @Provides
    fun provideApollo(
        okHttpClient: OkHttpClient,
        application: Application,
    ): ApolloClient {
      return ApolloClient.Builder()
          .okHttpClient(okHttpClient)
          .serverUrl(SERVER_URL)
          .httpCache(
              directory = application.cacheDir.resolve("apollo-cache"), // Performs File IO immediately
              maxSize = CACHE_SIZE_BYTES,
          )
          .build()
    }
```

DI provider functions should be safe to call on the main thread. However, since the `directory` argument of `httpCache()` is of type `File`, the `File` has to be created on the current thread in a blocking manner. On Android, this can lead to a Strict Mode `DiskReadViolation`. It would be great if `httpCache()` could provide an overload that allows for the following:

```Kotlin
    @Singleton
    @Provides
    fun provideApollo(
        okHttpClient: OkHttpClient,
        application: Application,
    ): ApolloClient {
      return ApolloClient.Builder()
          .okHttpClient(okHttpClient)
          .serverUrl(BASE_SERVER_URL)
          .httpCache(
              directoryProducer = {
                // Where this lambda gets invoked off the main thread via Apollo's dedicated Dispatcher
                application.cacheDir.resolve("apollo-cache")
              },
              maxSize = CACHE_SIZE_BYTES,
          )
          .build()
    }
```

Where `directoryProducer` is of type `() -> File`.

An API that this would draw inspiration from would be Jetpack DataStore's [DataStoreFactory.create(…)](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:datastore/datastore-core/src/jvmMain/kotlin/androidx/datastore/core/DataStoreFactory.jvm.kt;l=56-68?q=DataStoreFactory&ss=androidx).

**Comment by jerelmiller** [comment]
Hey @mhernand40 👋 

We have shifted this repo to be specific to the [Apollo TypeScript Client](https://github.com/apollographql/apollo-client). As such, I'm going to go ahead and close this issue.

If you're still interested in this feature request, please post this over in the [Apollo Kotlin](https://github.com/apollographql/apollo-kotlin) repo. Thanks!
