### ISSUE TITLE
Global variables or referencing context in gql variables

### ISSUE THREAD

**Issue by Minishlink** [apollographql/apollo-feature-requests#354]
Hello,

There are some use cases where it would simplify a lot the codebase if one could have global variables in queries/mutations, or use the context as a variable, mostly for directives. For example with feature flags, one can use them to do `@include(if: $FEATURE_FLAG_MY_FEATURE)` in fragments. Currently, you'd have to add `$FEATURE_FLAG_MY_FEATURE` to every queries/mutatitions/cache update possible, in your code but also in your test mocks. That can take a lot of time for a large codebase.

One could add `@include(if: $FEATURE_FLAG_MY_FEATURE)` or `@include(if: $global.FEATURE_FLAG_MY_FEATURE)` or `@include(if: $context.FEATURE_FLAG_MY_FEATURE)` to fragments. And then all your queries/mutations/cache updates use the Apollo context to get the variable.

Pros/cons of each solution:

* `@include(if: $FEATURE_FLAG_MY_FEATURE)`
  * pros: no breaking change. Adds a new variables or globalVariables to apollo client.
  * cons: ambiguity for the developer who is not aware of global variables
* `@include(if: $global.FEATURE_FLAG_MY_FEATURE)` or `@include(if: $context.FEATURE_FLAG_MY_FEATURE)`
  * pros: no ambiguity.
  * cons: breaking for people who have an existing variable with this name (maybe it's not possible?)

**Comment by jerelmiller** [comment]
Hey @Minishlink 👋 

Take a look at the [`defaultOptions`](https://www.apollographql.com/docs/react/api/core/ApolloClient/#defaultoptions) option that you can pass to the `ApolloClient` constructor. You can set `variables` using the `watchQuery` or `query` options, which does what you're trying to accomplish.

```ts
const client = new ApolloClient({
  defaultOptions: {
    watchQuery: {
      variables: { a: true, b: 'foo' }
    }
  }
})
```

If you need to perform this async, take a look at the creating a custom [Link](https://www.apollographql.com/docs/react/api/link/introduction) that would allow you to lookup values you need and pass update the outgoing `operation.variables` with the global options you're looking for. Here is a rough idea what that might look like:

```ts
const globalVariableLink = new ApolloLink(async (operation, forward) => {
  const globalVariables = await lookupGlobalVariables();

  return forward({
    ...operation, 
    variables: { ...operation.variables, ...globalVariables }
  });
}}
```

Let me know if either of those two solutions fit your need. If not, would you provide some more detail on what you're looking for!

**Comment by Minishlink** [comment]
Thanks! It does the job indeed :)

One thing that I see is that all default variables are sent in the HTTP requests even though, the variable is not referenced in the query. So if you have many global variables, they will all be copied in every queries even though they don't necessarily use them.

**Comment by jerelmiller** [comment]
@Minishlink interesting! Are you using `HttpLink` by chance? It's supposed to be stripping out [unused variables](https://github.com/apollographql/apollo-client/blob/main/src/link/http/createHttpLink.ts#L98-L119) (this is the [default behavior](https://github.com/apollographql/apollo-client/blob/2f79f03f1239b0496ddda938bf74a1b0ef97966e/src/link/http/createHttpLink.ts#L37)) so its surprising to me that you're seeing these variables make it through. Perhaps something else is at play? Regardless, glad the above works for you!

**Comment by Minishlink** [comment]
@jerelmiller Most of our queries are made with BatchHttpLink and not HttpLink, maybe there's a bug there? I'll check this

**Comment by jerelmiller** [comment]
@Minishlink gotcha! Looks unfortunately like we don't apply the same treatment in the batch link as we do in the http link. I don't see any reason why we shouldn't allow the same behavior across both. Would you be willing to open a new issue in the [client repo](https://github.com/apollographql/apollo-client) mentioning that batch http link should have this same behavior? I think its a good default.
