### ISSUE TITLE
Set option `cache: new InMemoryCach()` by default when instantiating of apollo client

### ISSUE THREAD

**Issue by thilllon** [apollographql/apollo-feature-requests#355]
We suggest that apollo client should give `cache` option's default value as `new InMemoryCache()` when instantiating the apollo client. Every docs, odyssey and tutorials set the `cache` option as `new InMemoryCache()`. So it would be simpler if cache option has default value.

https://www.apollographql.com/docs/react/caching/cache-configuration/
![image](https://user-images.githubusercontent.com/44559468/212388857-79fc1efd-c6af-4741-8e4c-e7a8de5149a3.png)

Thanks.

**Comment by alessbell** [comment]
Hi @thilllon 👋 

While it may seem innocuous to use `new InMemoryCache()` as the default `cache` value, one undesirable implication would be that the `InMemoryCache` class could not be treeshaken out of bundles for those who don't need it. For that reason, we won't be moving forward with this suggestion.
