### ISSUE TITLE
A way to chunk split field policies and dataIdFromObject

### ISSUE THREAD

**Issue by jedwards1211** [apollographql/apollo-feature-requests#359]
The field policies feature of the cache in Apollo 3 is helpful, but seems not scalable.  As far as I can see we need to define all field policies when we create the cache.  But as the number of field policies increases the initial page load size increases.  It would be nice to be able to chunk split field policies and only load them later as needed.  There would be decisions to make about an API for loading and installing more field policies, it certainly wouldn't be simple...

The same goes for dataIdFromObject.  Every time we need to support a new object type the amount of code in the initial page load increases.

**Comment by jerelmiller** [comment]
Hey @jedwards1211 👋 

It is actually possible today to add additional type policies after the creation of `InMemoryCache`. Unfortunately our docs don't really spell this out, so its a bit of a hidden feature.

Once you create the cache, you can use the `addTypePolicies` function on the `policies` property to add additional properties. This looks something like this:

```ts
const cache = new InMemoryCache({
  typePolicies: {
    Movie: {
      keyFields(incoming) {
        return `MotionPicture::${incoming.id}`;
      },
    },
  },
});

cache.policies.addTypePolicies({
  Movie: {
    fields: {
      isPurchased() {
        return false;
      },
    },
  },
});
```

In fact, you can see this in our tests here: https://github.com/apollographql/apollo-client/blob/a0ef4138478fb556b5f5f65c5ad7a1f8ac0274b6/src/cache/inmemory/__tests__/policies.ts#L452-L477.

If you find effective ways of code splitting some of these type policies in a way that would allow you to avoid some of the initial bundle size, this API should help you.

---

Given this API exists, I'm curious if this would satisfy what you're looking for? I'll see if we can find a way to get this documented in the mean time.

**Comment by jerelmiller** [comment]
Hey @jedwards1211 👋 

Given my [previous comment](https://github.com/apollographql/apollo-feature-requests/issues/359#issuecomment-1507774399) and my understanding of the request, this is possible today. I'm going to go ahead and close out this issue.

If I'm misunderstanding your request or you'd like to provide more information for us to consider, feel free to reopen. Thanks!
