### ISSUE TITLE
There's a typo in testing.md at line 17. It should be "Instead, it allows you" instead of "Instead, you"

### ISSUE THREAD

**Issue by AmulGaurav** [apollographql/apollo-feature-requests#360]
There's a little grammatical error in testing.md at line 17. It should be "Instead, it allows you" instead of just "Instead, you". It provides more meaning to the user.

**Comment by jerelmiller** [comment]
Hey @AmulGaurav 👋 

Would you be able to provide a link where you're seeing this? It's not clear if this is Apollo Client web, iOS, or Kotlin. Thanks!

**Comment by AmulGaurav** [comment]
Here's the link for the same: https://www.apollographql.com/docs/react/api/react/testing/#mockedprovider

But I think the typo is fixed now. Thanks for responding @jerelmiller 😃
It's the first time I tried to contribute. So, my apologies if there's something wrong with my PR.

![Screenshot 2023-04-07 145306](https://user-images.githubusercontent.com/116025402/230584132-f79242eb-b0de-4834-a959-4fc585821007.png)

**Comment by jerelmiller** [comment]
Glad to see its fixed! Good to know there was a reason I was having trouble finding it 😂. You're welcome to contribute anytime! We'd be more than happy to help out with any PR. Thanks a bunch!
