### ISSUE TITLE
Remove React dependency when importing gql from @apollo/client

### ISSUE THREAD

**Issue by gengns** [apollographql/apollo-feature-requests#399]
# Docs
The @apollo/client package includes graphql-tag as a dependency and re-exports gql. To simplify your dependencies, **we recommend importing gql from @apollo/client and removing all graphql-tag dependencies.**

# Issue
After importing gql from @apollo/client and removing all graphql-tag dependencies. 
```bash
-import { gql } from 'graphql-tag'
+import { gql } from '@apollo/client'
```
We get React dependency errors.
```bash
✘ [ERROR] Could not resolve "react"

    node_modules/@apollo/client/react/hooks/useReadQuery.js:1:23:
      1 │ import * as React from "react";
```

# History
This feature/bug is supposed to be fixed.
- https://github.com/apollographql/apollo-client/issues/6532
- https://github.com/apollographql/apollo-client/issues/8190

# Stack
- bun@1.0.0
- vite@4.4.9
- svelte@4.2.1
- @apollo/client@3.8.4

**Comment by phryneas** [comment]
If you don't want the `react` dependency, you can `import { gql } from "@apollo/client/core"`

**Comment by gengns** [comment]
Awesome @phryneas, thank you so much.
