### ISSUE TITLE
Please add polyfill for `globalThis` as it breaks compatibility for Chrome < v71

### ISSUE THREAD

**Issue by kpervin** [apollographql/apollo-feature-requests#421]
For versions of `@apollo/client` 3.8.*, the use of `globalThis.__DEV__` was introduced. We have a chrome client that cannot be upgraded past v68 atm and this breaks compatibility by causing `ReferenceError: globalThis is not defined`. Please add a polyfill (possibly from https://polyfill.io/v3/polyfill.min.js?features=globalThis) to the output of `@apollo/client` so that this error is not encountered on older browsers.

**Comment by alessbell** [comment]
Hi @kpervin 👋 Have you seen our docs on [reducing bundle size](https://www.apollographql.com/docs/react/development-testing/reducing-bundle-size)? You can remove `globalThis.__DEV__` at build time.

**Comment by kpervin** [comment]
That looks to have fixed the issue, thanks!
