### ISSUE TITLE
Keyword search in Job postings filter

### ISSUE THREAD

**Issue by rushinsurotia** [apollographql/apollo-feature-requests#424]
Could you put an option for keyword search in the job posting filter? It would be better if we could do a Boolean operator search. There are several advantages to this as it helps dive deeper into more specifics of the open jobs. Thank you.

**Comment by jerelmiller** [comment]
Hey @rushinsurotia 👋 

This repository is for Apollo Client feature requests and does nothing with job postings. Apologies if this repo gave you that impression! As such, I'm going to go ahead and close this. Thanks!
