### ISSUE TITLE
Support of file uploads in apollo-boost

### ISSUE THREAD

**Issue by robsdedude** [apollographql/apollo-feature-requests#51]
Migrated from: apollographql/apollo-client#3161

apollo-boost should imho support file uploads (https://github.com/jaydenseric/apollo-upload-client) as this is a very common need for clients.

**Comment by WickyNilliams** [comment]
I think more generally, the feature should be to allow arbitrary links with apollo-boost. 

I understand that order is important, so perhaps if you set a `link` option you should be in charge of configuring order of all links. To simplify the process (and still reap benefits of boost's defaults), some helpers could be exported from boost. Using the example above of integrating the upload client, you could do this:

```js
import ApolloClient, {
  createErrorLink,
  createRequestLink,
  InMemoryCache
} from "apollo-boost";

const client = new ApolloClient({
  link: ApolloLink.from([
    createErrorLink(),
    createRequestLink(handleRequest),
    createUploadLink({ uri: process.env.API_URL })
  ])
});
```

These same functions could be called internally in `apollo-boost` for the case where a `link` option is not passed

**Comment by sgentile** [comment]
Would like to see this pursued by apollo-boost, it's a shortcoming that needs to be addressed in order to support file uploading.   I spend hours trying to get this all to work to only find out apollo-boost doesn't support this.

**Comment by dylanwulf** [comment]
In Apollo Client v3, I believe the plans are to get rid of apollo-boost completely. The main apollo-client package will have its API simplified in order to compensate for this. v3 is currently in beta, and you can try it out by installing the `@apollo/client` package.

**Comment by sgentile** [comment]
Thank you

**Comment by sgentile** [comment]
@dylanwulf  While attempting to use @apollo/client I'm getting this error :

This is using import { createUploadLink } from 'apollo-upload-client'; because I don't see any options with @apollo/client to provide support for file uploads.

error:

Type 'ApolloLink' is missing the following properties from type 'ApolloLink': onError, setOnError  TS2739
```
const apolloClient = new ApolloClient({
        link: createUploadLink({
            uri: '/api',
            headers: {
                authorization: token ? `Bearer ${token}` : '',
            },
        }),
        cache: new InMemoryCache(),
    });
```

**Comment by dylanwulf** [comment]
Oh sorry, I guess the maintainer of `apollo-upload-client` hasn't updated it to be compatible with v3 yet 🙁

**Comment by leorigon** [comment]
Any update about this feature/request?

**Comment by hwillson** [comment]
Apollo Boost has been deprecated. General details about handling file uploads with Apollo Client/Server can be found here: https://www.apollographql.com/blog/graphql/file-uploads/with-react-hooks-typescript-amazon-s3-tutorial/
