### ISSUE TITLE
Add listeners for `clearStore()`

### ISSUE THREAD

**Issue by SnidelyWhiplash** [apollographql/apollo-feature-requests#53]
Happy to see [the new `clearStore()` method](https://github.com/apollographql/apollo-client/pull/3885). I think one way to improve this is to be able to add listeners (via `client.onClearStore`) like we can with `resetStore()`.

My use-case is being able to clear `apollo-cache-persist` when I call `clearStore()` from my logout flow.

**Comment by hwillson** [comment]
@SnidelyWhiplash Sure thing - we'd love to see that. Pull requests encouraged if you're interested! 🙂

**Comment by hwillson** [comment]
Addressed in https://github.com/apollographql/apollo-client/pull/4082.
