### ISSUE TITLE
Add proper query invalidation

### ISSUE THREAD

**Issue by darren128** [apollographql/apollo-feature-requests#67]
Migrated from: apollographql/apollo-client#2895

Per @clayne11

> After investigating a pretty confusing performance problem in one of my apps, I came across a pretty serious issue.
> 
> As far as I can tell, every time any query or mutation occurs every single component that is watching any data in the apollo store gets re-rendered, even if none of its data has changed.
> 
> Imagine an e-commerce scenario: I favorite an item for later, which calls a mutation to save that favorited item on my account.
> 
> As a result, my entire page re-renders with hundreds of items since they're all being read from the apollo store, even though none of them have changed. This can take a few hundred milliseconds on a mobile device and cause stuttering and janking.
> 
> Intended outcome:
> Each query's dependency graph is fully traversed and only updated if an object within that graph has changed.
> 
> Actual outcome:
> Every single query is invalidated and re-run causing every component listening to any query in the store to re-render.

**Comment by clayne11** [comment]
This was resolved a few weeks ago in a PR from benjamn. This can be closed.
