### ISSUE TITLE
Dedup subscriptions

### ISSUE THREAD

**Issue by thomassuckow** [apollographql/apollo-feature-requests#74]
When multiple parts of the UI utilize the same subscription it will be subscribed to for each occurance.

This increases latency to the user because it doesn't pull from the cache and increases network traffic due to duplicated payloads.

There already appears to be a start at deduplicating in QueryManager, it utilizes an observables array despite it always containing 0 or 1 observable.

**Comment by lorensr** [comment]
For example, I have a `<Subscription subscription={ON_NEW_CHAT}>` in `NewMessageNotification.js` and a `subscribeToMore({ document: ON_NEW_CHAT })` in `Channel.js`. I see in the websocket traffic that this creates two identical subscriptions.

**Comment by benjamn** [comment]
For the record, the only thing currently stopping this from working is that we explicitly disable deduplication for subscriptions by passing `false` for the `deduplication` parameter of `getObservableFromLink` [here](https://github.com/apollographql/apollo-client/blob/34da93bd1134c59ca77cc3df2e76dfbf11a1df39/packages/apollo-client/src/core/QueryManager.ts#L960).

**Comment by thomassuckow** [comment]
Is there any reason it can't be `true`?

**Comment by benjamn** [comment]
@hwillson Any thoughts on deduplicating subscriptions by default?

**Comment by hwillson** [comment]
@benjamn I'm all for it (and we should be safe to deduplicate subscriptions in a minor/patch release).

**Comment by qeternity** [comment]
Any word on this release? What's the current best practice to have multiple components received subscription events?

**Comment by dmaskasky** [comment]
@hwillson @benjamn @jpikora 

I am composing useSubscription into a custom react hook.  For each call position where the hook is used, a new subscription is created.  This deduplication issue is compounded with the addition of @apollo/react-hooks.

**Comment by jkossis** [comment]
Any movement on setting this to true? Would really help performance!

**Comment by thomassuckow** [comment]
QueryManager has evolved quite a bit. I do now see a constructor parameter, though I am not sure what it takes to set it. https://github.com/apollographql/apollo-client/blob/8c1d8b4dc5ac964dd791bf635918309aa1474b70/src/core/QueryManager.ts#L88

Personally I'm not in a position to dive too deep into this at the moment since client 3 is not playing nice with our app so we are trying to mitigate that first. The GraphQL spec is so bloody complex, I'm tempted again to move to making a graphql-lite in yaml without aliases.

**Comment by ntziolis** [comment]
The PR #6910 that enables this is ready and waiting for approval / comments since quite a while, any reason this hasn't been merged in.
