### ISSUE TITLE
Exporting as ES Module Syntax (ESM)

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-feature-requests#83]
Please, export `"module"` entry point in the `package.json` as ES Module Syntax (ESM).

More info about it here: https://www.pikapkg.com/about/

JIRA link: https://apollographql.atlassian.net/rest/api/2/issue/10171

**Comment by JoviDeCroock** [comment]
I have implemented this for `react-apollo` in https://github.com/apollographql/react-apollo/pull/2677
It's being handled in `apollo-client` in https://github.com/apollographql/apollo-client/pull/4261

**Comment by benjamn** [comment]
I think this is done!
