### ISSUE TITLE
Expose hook to updateQuery after running fetchQuery

### ISSUE THREAD

**Issue by pl12133** [apollographql/apollo-feature-requests#92]
**Motivation**

This feature aims to solve the undesired behavior that occurs when a paginated query is refetched: https://github.com/apollographql/apollo-client/issues/4068

When a paginated query is refetched, any pages that have been added to the query using `fetchMore` will be cleared from the cache: https://codesandbox.io/s/yw5qrm5o8z

This would make it simpler to have a paginated query that adds items to either the head or the tail.

**Summary**

Currently the `updateQuery` function is used by `fetchMore` to merge new results into an existing query. There is no corresponding way to merge results from `refetch` or a network-type `fetchPolicy`.

This feature would move `updateQuery` to be a top level option instead of an option for `fetchMore`, and optionally run `updateQuery` after every query.

**Implementation**

After `fetchQuery` is called in either `setVariables` or `refetch`, optionally call `this.options.updateQuery` with the old and new query results and write the results to the store.

https://github.com/apollographql/apollo-client/blob/98a5cedaa63ea57abdd1f45514e024f319aea27a/packages/apollo-client/src/core/ObservableQuery.ts#L521

https://github.com/apollographql/apollo-client/blob/98a5cedaa63ea57abdd1f45514e024f319aea27a/packages/apollo-client/src/core/ObservableQuery.ts#L325

**Comment by maitriyogin** [comment]
Hi, just wondering if there's any traction on this?
/Stephen.

**Comment by pl12133** [comment]
This will soon be solved by the new [Field Policy](https://www.apollographql.com/docs/react/v3.0-beta/caching/cache-field-behavior/#handling-pagination) option, giving more control over merging paginated fields.

I think this is safe to close once 3.0 is out of beta.

**Comment by jerelmiller** [comment]
Hey all 👋 

Given [this comment](https://github.com/apollographql/apollo-client/pull/10502) and the fact that 3.0 has been out for some time now, I'm going to go ahead and close this issue as completed. Feel free to open an additional feature request for more modern versions of Apollo if you'd like more assistance or to propose a new idea. Thanks!
