### ISSUE TITLE
Pass context from subscription to link

### ISSUE THREAD

**Issue by sgtpepper43** [apollographql/apollo-feature-requests#93]
[This line](https://github.com/apollographql/apollo-client/blob/17cbf64b5a4de2d8ea180145a484481799daab25/packages/apollo-client/src/core/QueryManager.ts#L943) has a `TODO` that says
> Should subscriptions also accept a `context` option to pass through to links?

I say yes. Unless we can find a more generic solution to the problem we're having. So here's the use case:

We have a list of chat messages, and we use `subscribeToMore` to get any new chat messages. On a mobile device (this is also true on web, but more common on mobile), if you lock your screen for long enough, the app becomes inactive and the socket disconnects. When the screen comes back on, the socket reconnects, and we can get new messages down the socket. _But_, there's no mechanism to fetch the messages that you missed while the phone was locked. Our solution is to pass an `onReconnect` function down to our socket link that will refetch the list of items in the case that the socket disconnects and reconnects. 

This should be a pretty straightforward change, shouldn't break any existing code, and actually brings `subscribeToMore` more inline with the api of all the other graphql requests.

**Comment by telnicky** [comment]
+1 would love to see this land, our workaround for this makes it difficult to mock subscriptions in tests with the `MockProvider`.

**Comment by sgtpepper43** [comment]
I would be more than happy to make a pull request for this, I'd rather just get approval for the feature first.

**Comment by hwillson** [comment]
@sgtpepper43 We would love a PR for this - thanks very much!

**Comment by edmundas-ramanauskas** [comment]
+1
I think there needs to be changes made in `react-apollo` repository as well. I tried to do that, but I can't build the project - getting error: https://pastebin.com/p1m5wfTg

**Comment by karice** [comment]
I'm looking for the same thing. Currently, using context on queries to switch between clients.

Example using react hooks:
// Subscription
const {
    statusData,
    loading: isStatusLoading,
    error: statusError
  } = useSubscription(getStatus, {
    context: { clientName: 'my first client' },
    variables: { id: '123' }
  })

// Link
link = ApolloLink.split(
      (operation) => {
        const isClient1 = ((operation && 
          operation.getContext() && 
          operation.getContext().clientName && 
          operation.getContext().clientName === 'my first client')
        return isClient1;
      },
      clientLink1,
      clientLink2
    )

The PR from sgtpepper43 looks like it would do the trick.
