### ISSUE TITLE
SSR support for apollo-boost

### ISSUE THREAD

**Issue by ajhool** [apollographql/apollo-feature-requests#96]
Currently Apollo Boost does not appear to support SSR or the config option: `{ssrMode: true}`.  This is related to #15 .

**Comment by jerelmiller** [comment]
Hey @ajhool 👋 

`apollo-boost` is now deprecated. I know this issue is a bit old so I'm going to go ahead and close this. Feel free to open a new feature request if you want to request additional functionality for modern versions of Apollo Client. Thanks!
